arch-x86: Add XCR0 register and add to X86KvmCPU
gem5/gem5 pull request #1040
Opened 2024-04-19 17:26 UTC by abmerop

The extended control registers were not being updated in the KVM thread context nor updated in the KVM state. This was causing issues when checkpointing since the XCR0 value was reverting to the default value rather than what it was previously before the checkpoint. THis was causing multiple applications to crash due to executing instructions which are now illegal instructions due to XCR0 being incorrect.

This commit adds the XCR0 as a misc register similar to the exiting x86 control registers and adds all of the helper functions to access and set the register value. It also adds support for updating the KVM CPU's state with the register value and updating the thread context's misc reg value so that it is checkpointed along with the other misc regs.

Note that this does *not* add support for XSAVE of the AVX state (i.e., the upper 128 bits of YMM registers). It does however fix the immediate problem in issue #958 .

Change-Id: I97456c8b57cbc7b381bd4be94944ce6567a43c76

2024-04-19 17:27 UTC, abmerop commented
@v-ramadas I stumbled upon a solution to this kernel panic while working on something slightly related, so created a PR for it.  We should be able to test checkpointing GPU ML apps now

2024-04-19 19:47 UTC, v-ramadas commented
Thanks! This is great. I will test it out when I get some time.

2024-04-20 16:41 UTC, mattsinc requested changes
Amazing!  Just one small thing,

2024-04-20 16:41 UTC, mattsinc commented on src/arch/x86/fs_workload.cc
> +    xcr0.x87 = 1; // Must be 1
Ideally it would be good to explain why it must be 1

2024-04-20 16:41 UTC, mattsinc commented on src/arch/x86/regs/misc.hh
> +    XcrBase,
it's a little weird that you declare XcrBase, then set it to the Xcr0 in the next line, but I guess if it works ok

2024-04-20 18:07 UTC, abmerop commented on src/arch/x86/regs/misc.hh
> +    XcrBase,
Just following the style above with the other groups of registers.  There just happens to only be one XCR register

2024-04-20 18:08 UTC, abmerop commented on src/arch/x86/fs_workload.cc
> +    xcr0.x87 = 1; // Must be 1
Added comments

2024-04-21 15:23 UTC, abmerop commented
@BobbyRBruce @Harshil2107  The failing tests are checkpoint restore checks.  The checkpoint appears to be part of a resource, how does that get updated?  This change implicitly adds another element to an array param

2024-04-21 21:37 UTC, mattsinc approved these changes, later dismissed

2024-04-25 14:26 UTC, abmerop commented
.... Do I need to write a checkpoint upgrader?

2024-04-25 17:04 UTC, Harshil2107 commented
If the checkpoint upgrader needs to be updated, then I can run the updated checkpoint upgrader on the existing checkpoints and push a new version. If the checkpoint upgrader doesnt need to be update I can just retake the checkpoints and update the version.

Can you tell me if you need to update the checkpoint upgrader?

2024-04-25 17:07 UTC, abmerop commented
Well if you take new checkpoint *with this change applied* then that would also fix the failing tests.

I suppose writing an upgrader is more correct as other might need to use it.  Is the upgrader run as part of the tests?

2024-04-25 17:37 UTC, abmerop commented
> If the checkpoint upgrader needs to be updated, then I can run the updated checkpoint upgrader on the existing checkpoints and push a new version. If the checkpoint upgrader doesnt need to be update I can just retake the checkpoints and update the version.
> 
> Can you tell me if you need to update the checkpoint upgrader?

Added a checkpoint upgrader.  I guess this would have to be applied to the resources?

2024-04-25 17:47 UTC, Harshil2107 commented
I will run and update the failing checkpoints.

2024-04-25 17:52 UTC, abmerop commented
> I will run and update the failing checkpoints.

Thank you!

2024-04-25 20:45 UTC, Harshil2107 commented
I just reran the tests with updated checkpoints.

2024-04-25 21:07 UTC, Harshil2107 commented
To get the tests to pass you would need to update the resource version to 3.0.0 in the x86-fs-restore-checkpoint.py, x86-hello-restore-checkpoint.py. I can also push a commit with this changes if you want me to.

2024-04-25 21:09 UTC, abmerop commented
> To get the tests to pass you would need to update the resource version to 3.0.0 in the x86-fs-restore-checkpoint.py, x86-hello-restore-checkpoint.py. I can also push a commit with this changes if you want me to.

Sure... I don't know where those files are.

2024-04-29 16:37 UTC, Harshil2107 commented
The checkpoint upgrader doesnt seem to fix the checkpoints, should I take new checkpoints or do we need to update the updater again?

2024-04-29 17:22 UTC, abmerop commented
It looks like the testlib tests have a different name for the ini config section, so I will have to rewrite the upgrader

2024-04-29 17:58 UTC, abmerop commented
Updated the checkpoint upgrader.  You might need to manually edit the m5.cpt file to remove the x86-add-xcr0 tag from the file before running the upgrader again.  Or simply use the 2.0.0 files

2024-05-03 15:55 UTC, abmerop commented
If I could make a suggestion.  Is it possible to have testlib run the checkpoint upgrader before running a test? Then you could "officially" recreate during the release freeze? That way it wouldn't require someone with access to the checkpoint files to post a PR requiring checkpoint upgrades.  Although that might be rare enough it doesn't make sense.

2024-05-03 16:39 UTC, Harshil2107 commented
The updated simpoint is causing other PRs to fail, I will create create a version specific resource for this PR and so that the tests in other PRs dont fail.

2024-05-03 17:58 UTC, Harshil2107 commented
> If I could make a suggestion. Is it possible to have testlib run the checkpoint upgrader before running a test? Then you could "officially" recreate during the release freeze? That way it wouldn't require someone with access to the checkpoint files to post a PR requiring checkpoint upgrades. Although that might be rare enough it doesn't make sense.

The reason for not doing that is, that the checkpoints on gem5 resources become outdated and need to be updated all at once. As we have to keep the checkpoints in sync with gem5 resources, I feel it is better to keep on updating them as the changes are made. 

I will push a change that defines the resource versions explicitly instead of grabbing the latest version in another PR. In this way the tests for other PRs with older code will not fail, when we update the checkpoints.

2024-05-03 17:59 UTC, Harshil2107 commented
I have created a new resource for this change, now the tests in other PRs should not be affected. I will sync the resources when I push the PR I mentioned above (this should not affect tests for other PRs).

2024-05-03 18:02 UTC, abmerop commented
> > If I could make a suggestion. Is it possible to have testlib run the checkpoint upgrader before running a test? Then you could "officially" recreate during the release freeze? That way it wouldn't require someone with access to the checkpoint files to post a PR requiring checkpoint upgrades. Although that might be rare enough it doesn't make sense.
> 
> The reason for not doing that is, that the checkpoints on gem5 resources become outdated and need to be updated all at once. As we have to keep the checkpoints in sync with gem5 resources, I feel it is better to keep on updating them as the changes are made.
> 
> I will push a change that defines the resource versions explicitly instead of grabbing the latest version in another PR. In this way the tests for other PRs with older code will not fail, when we update the checkpoints.

I see. I was attempting to find a solution that didn't require a single entity (UC Davis) to have to be involved.

2024-05-03 18:19 UTC, powerjg commented
> I see. I was attempting to find a solution that didn't require a single entity (UC Davis) to have to be involved.

Thanks! I agree that would be great. The main problem here is that checkpoints are deeply tied to the code of gem5 (which is a problem). Really, checkpoints should be more of an API that can't be changed willy-nilly, but that's not how it's architected right now.

There's a tradeoff in the work to do per-commit and per-release. When possible, I'd like to do the work per-commit to make release time easier. Updating checkpoints should be rare enough (a few times every release) that it's better to do it per-commit than waiting until the release.

You're not the first to suggest auto-running the checkpoint upgrader (or removing checkpointing from testing). But, one of the main arguments against this is that it would mask when checkpoints need to be updated for the next release (putting more onus on us at release time).

2024-05-05 22:06 UTC, mattsinc commented
@abmerop it doesn't look like you need me for anything here at this point, since you are still working with @Harshil2107 on the checkpoint changes.  Let me know if I'm missing something though.  I added Harshil as a review to hopefully help with this.

2024-05-06 14:34 UTC, abmerop commented
> @abmerop it doesn't look like you need me for anything here at this point, since you are still working with @Harshil2107 on the checkpoint changes. Let me know if I'm missing something though. I added Harshil as a review to hopefully help with this.

The checks has passed now, so I just need a reviewer to approve

2024-05-06 15:05 UTC, mattsinc approved these changes
Probably @Harshil2107 or @powerjg should approve too?

2024-05-06 16:48 UTC, Harshil2107 approved these changes
lgtm

2024-05-06 16:58 UTC, merged