mem: Make functional request a response when satisfied by queue
gem5/gem5 pull request #119
Opened 2023-07-25 15:32 UTC by atrib

In the memory controller, MemCtrl::MemoryPort::recvFunctional, when the functional request is satisfied by the ctrl-response queue, correctly make the packet a response.

This change mirrors AbstractMemory::functionalAccess, which uses Packet::makeResponse() after satisfying the request.

Note:
`bool trySatisfyFunctional(..)` functions return `true` or `false` based on whether the request was satisfied.
`void recvFunctional(..)` functions modify the packet to indicate successful request satisfaction.

2023-07-25 23:20 UTC, powerjg requested changes
One small style thing and a suggested comment to add. Otherwise, this change looks good to me.

2023-07-25 23:20 UTC, powerjg commented on src/mem/mem_ctrl.cc
> +        pkt->makeResponse();
```suggestion
    } else {
        // If the packet is found in the queue, the queue does not makeResponse
        pkt->makeResponse();
    }
```

2023-07-26 15:05 UTC, powerjg commented
As far as I can tell, nothing changed in the PR. I'm not sure if you intended to make updates or not :). Let me know when you're "done" and I'll start the CI tests.

2023-07-26 15:08 UTC, atrib commented
I only changed the comment text, so no new CI tests should be necessary. 
I am "done", as in I do not have any more changes to add.

First time submitting a pull request, so apologies if I did something incorrectly.

2023-07-26 15:09 UTC, atrib commented on src/mem/mem_ctrl.cc
> +        pkt->makeResponse();
Small change to comment text for clarity.

```suggestion
    } else {
        // The packet's request is satisfied by the queue, but queue does not call makeResponse
        // Here, change the packet to the corresponding response
        pkt->makeResponse();
    }
```

2023-07-26 15:14 UTC, powerjg approved these changes, later dismissed
Thanks!

2023-07-26 15:23 UTC, atrib commented
Sorry, this is now a mess. To make our lives easier, I will just create a new, clean PR

2023-07-26 15:23 UTC, closed without merging