misc: Change devcontainer for isca tutorial
gem5/gem5 pull request #1282
Opened 2024-06-24 19:19 UTC by powerjg

Change-Id: I4e946bf32b5ad362ff34de5d354fe29cd26fc0cb

2024-06-24 19:20 UTC, powerjg commented
Just for posterity to track the changes I made.

2024-06-25 17:28 UTC, BobbyRBruce requested changes

2024-06-25 17:28 UTC, BobbyRBruce commented on util/dockerfiles/devcontainer/Dockerfile
> +    COPY --from=builder /gem5/build/VEGA_X86/gem5.opt /usr/local/bin/gem5-vega
There is a weird leading whitespaces here.

```suggestion
COPY --from=builder /gem5/build/ALL/gem5.opt /usr/local/bin/gem5-default
COPY --from=builder /gem5/build/ALL_CHI/gem5.opt /usr/local/bin/gem5
COPY --from=builder /gem5/build/VEGA_X86/gem5.opt /usr/local/bin/gem5-vega
```

2024-06-25 17:28 UTC, BobbyRBruce commented on util/dockerfiles/devcontainer/Dockerfile
> +RUN apt -y install wget
```suggestion
    libhdf5-serial-dev python3-pydot libpng-dev libelf-dev pkg-config wget
```

2024-06-25 17:28 UTC, BobbyRBruce commented on util/dockerfiles/devcontainer/Dockerfile
> +RUN apt -y install gcc-riscv64-linux-gnu
1. Best to run any `apt` command with the `-y` flag.
2. `apt` `update` and `install` commands should always be in a single `RUN`.
3. Where possible `install` commands should be merged to reduce the Docker image size.

```suggestion
RUN apt -y update && apt -y install \
    # This package should be the minimum needed to build and is significantly
    # smaller than the full `rocm` package.
    rocm-dev \
    # Installs the cross compilers.
    gcc-aarch64-linux-gnu \
    gcc-riscv64-linux-gnu
```

2024-06-25 17:28 UTC, BobbyRBruce commented on util/dockerfiles/devcontainer/Dockerfile
>  # Stage 2: The final stage where we create the devcontainer image.
```suggestion
# Stage 2: Create the devcontainer image.
```

2024-06-25 17:28 UTC, BobbyRBruce commented on util/dockerfiles/devcontainer/Dockerfile
>  # dependencies for developing gem5, and a pre-built gem5 binary.
```suggestion
# dependencies for developing gem5, and the pre-built gem5 binaries.
```

2024-07-17 00:53 UTC, BobbyRBruce commented
Making some updates here. I'll let you know when ready for review.

2024-07-17 20:24 UTC, powerjg commented on util/dockerfiles/devcontainer/Dockerfile
> +    gcc-riscv64-linux-gnu
Can you add the following code? I'm not 100% sure what should go here vs in our startup script. This is necessary to get `menuconfig` to work.

```
apt-get update && apt-get install locales
locale-gen en_US.UTF-8
export LANG="en_US.UTF-8"
```

2024-07-17 20:24 UTC, powerjg commented on util/dockerfiles/devcontainer/Dockerfile
> +COPY --from=builder /gem5/build/ALL_CHI/gem5.opt /usr/local/bin/gem5
Let's name this `gem5-chi` and then do a symlink from gem5 to gem5-chi

```suggestion
COPY --from=builder /gem5/build/ALL_CHI/gem5.opt /usr/local/bin/gem5-chi
RUN ln -s /usr/local/bin/gem5-chi /usr/local/bin/gem5
```

2024-07-18 19:00 UTC, BobbyRBruce commented
Thanks Jason this PR and the dockerimage hosted on ghcr have been updated to incorporate this

2024-08-07 02:45 UTC, BobbyRBruce approved these changes

2024-08-07 02:45 UTC, merged