cpu: Add cpuIdlePins to indicate the threadContext of CPU is idle
gem5/gem5 pull request #1285
Opened 2024-06-25 08:24 UTC by rogerchang23424

If the threacContext of CPU enters the suspend mode, raise the threadID of threadContext cpu_idle_pins with the high signal to target. If the threadContext of CPU enters the activate mode, lower the threadID of thread cpu_idle_pins with low signal to target.

2024-06-26 12:56 UTC, giactra requested changes

2024-06-26 12:56 UTC, giactra commented on src/cpu/base.cc
> +      cpuIdlePins[thread_num]->lower();
4 whitespaces needed

2024-06-26 12:56 UTC, giactra commented on src/cpu/base.cc
> +      cpuIdlePins[thread_num]->raise();
Ditto

2024-06-26 12:56 UTC, giactra commented on src/cpu/BaseCPU.py
> +        "This signal indicates the thread context of CPU is idle"
It would be nice if we could document this further. For example, from an initial look at the way it is used it seems like there should be a 1:1 relation between pins and number of HW threads. However it looks like we allow for "silent" threads:


    if (thread_num < cpuIdlePins.size()) {
      cpuIdlePins[thread_num]->lower();
      
Means we can generate less pins and related threads won't generate any idle output... I would like this to be specified in the Param help string

2024-06-26 12:56 UTC, giactra commented on src/cpu/base.cc
> +      cpuIdlePins.emplace_back(new IntSourcePin<BaseCPU>(
4 whitespace needed

2024-06-27 03:17 UTC, rogerchang23424 commented on src/cpu/BaseCPU.py
> +        "This signal indicates the thread context of CPU is idle"
Please check the Param helping description, Thanks

2024-07-10 09:36 UTC, giactra approved these changes
Thanks for your changes

2024-07-10 09:36 UTC, merged