arch-arm: Fix implicit int-to-float conversion in VCMP
gem5/gem5 pull request #1326
Opened 2024-07-03 08:43 UTC by arichardson

Explicitly convert to float/double to fix compiler warnings that I have turned on locally. It might make sense to make use of fplib functions to be portable across different host float formats but something as simple as comparison against zero should be safe.

Change-Id: I96c6ee7c5497fece11be07234ff80ff86e7555e2

2024-07-10 10:52 UTC, giactra requested changes
Hi @arichardson thanks for this contribution. 
I believe one of the reasons why the code was written that way (using an imm instead of just comparing to zero) was to be able to reuse the snippet in other scenarios (with imm != 0). Can we just compare directly with zero? Ideally we should also change the instruction definition to not use an immediate but it is not worth the effort

2024-07-22 17:43 UTC, ivanaamit commented
@arichardson, could you please address Giacomo's comment? Thank you.

2024-08-12 14:23 UTC, ivanaamit commented
@arichardson, just a reminder to address Giacomo's review. Thanks!

2024-08-22 23:35 UTC, arichardson commented
Sorry for the delay, updated now.

2024-08-23 11:00 UTC, giactra approved these changes

2024-08-26 09:22 UTC, merged