Added implementation of IPCP prefetcher
gem5/gem5 pull request #1436
Opened 2024-08-08 16:06 UTC by Setu-Gupta

This PR adds the IPCP prefetcher described in [this ](https://ieeexplore.ieee.org/document/9138971) paper.

On branch ipcp
Changes to be committed:
	modified:   src/mem/cache/prefetch/Prefetcher.py
	modified:   src/mem/cache/prefetch/SConscript
	new file:   src/mem/cache/prefetch/ipcp.cc
	new file:   src/mem/cache/prefetch/ipcp.hh

Change-Id: Ie52a9602719773248aa17e9bc3d98203d9b1e23b

2024-08-26 17:04 UTC, AbhishekUoR commented
@ivanaamit: Is there a problem with this PR? How long should we expect it to be reviewed?

2024-09-09 17:26 UTC, ivanaamit commented
Hi @Setu-Gupta, I noticed you pushed some changes last week. Is this PR ready for review, or are you still working on it? Thanks.

2024-09-09 17:31 UTC, Setu-Gupta commented
Hi @ivanaamit

There are some aesthetic changes related to code formatting which are still remaining. I'll probabyly push them this week and let you know when the PR is ready for review. Right now I'm working on PR #1441

2024-10-31 18:57 UTC, erin-le commented
@Setu-Gupta Hello, I've noticed that you've pushed a few commits after your last message. Could you give an update on what the status of this PR is? Thanks!

2024-10-31 20:50 UTC, Setu-Gupta commented
Hi Erin

Most of the changes that I did were related just to code formatting. Unfortunately I haven't been able to find the time to test the code after the changes and so I'm not fully confident that the code behaves exactly like it used to before the changes. Once I verify this, then I'll open this PR for reviews.

2025-01-11 03:01 UTC, AbhishekUoR commented
@erin-le this PR is ready for review

2025-01-13 16:18 UTC, powerjg requested changes
I don't know much about the implementation of the prefetcher, so I'll assume that it's implemented correctly and has been tested. Below is a number of comments on code style.

I say this often, but I think it's worth repeating. When you write code, you're not writing it for the computer, you're writing code for future humans. So, it's important that the intentions in the code are clear *to humans*. This is why we have a strict code style and why it's often not worth saving a few characters here and there if it means that future humans looking at the code could be confused. Said another way, code is written once and read (by humans) many times. Let's optimize for the common case (humans reading the code), not the one-time case (writing the code).

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/ipcp.hh
> +               streamValid = false;
Initialization should be done in an initializer list or directly when the variables are declared, not in the constructor method.

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/ipcp.hh
> +           ~IpEntry() {}
Default destructors are not needed. You can say `~IpEntry() = default` to be more explicit (or have nothing).

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/ipcp.hh
> +           ~CsptEntry() {}
Ditto the two points above.

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/ipcp.hh
> +    bitsIpTag, bitsLastVpage, bitsSignature;
Confusing syntax. Just put each variable on its own line. We don't have to pay anyone per newline :)

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/ipcp.hh
> +           ~RstEntry() {}
Ditto the two points above.

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/ipcp.cc
> +                ipcpStats.pageCross += 1;
Use curly braces everywhere. It's particularly confusing (and can lead to hard to find bugs!) when sometimes you use curly braces for single line if statements and other times you don't.

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/ipcp.cc
> +        ipcpTable[ipIndex].conf -= 1;
Required to have curly braces for multi-line if statements. I have lost many hours of my life tracking down bugs because people wanted to save two characters. It's not worth it.

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/ipcp.cc
> +        //ipcpTable[ipIndex].conf = 4;
Why commented out?

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/ipcp.cc
> +                 || RST[regionBase].trained);
This seems to be resetting (or initializing) the entry. This should be a method on the entry since it's used in many different places.

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/ipcp.cc
> +    //Addr ipIndex = (hash1 ^ hash2) & ((1 << bitsIpIndex) - 1);
Why is this commented out? If it's documentation, then it needs more context for future people to understand. If it's not documentation, it should be removed.

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/ipcp.cc
> +     & ((1 << bitsSignature) - 1));
I think if/else would be much easier to read! Especially since the ternary statement goes over so many lines.

2025-01-13 16:18 UTC, powerjg commented on src/mem/cache/prefetch/Prefetcher.py
> +    # Paper: https://doi.org/10.1109/ISCA45697.2020.00021
Can you add an `add_citation` call for this. See https://github.com/gem5/gem5/blob/stable/src/mem/MemCtrl.py#L106 for an example.

2025-02-20 00:17 UTC, erin-le commented
@Setu-Gupta and @AbhishekUoR: Hello, could you guys respond to these comments when you have time and/or give an update on the status of this PR? Thank you!

2025-02-20 00:27 UTC, Setu-Gupta commented
Hi @erin-le 

I've been quite busy with other work so I haven't found time to work on my PRs. I'll try to get this done as soon as I find some time.

2025-04-07 06:07 UTC, AbhishekUoR commented on src/mem/cache/prefetch/ipcp.cc
> +        //ipcpTable[ipIndex].conf = 4;
was typo

2025-04-07 06:18 UTC, AbhishekUoR commented
@erin-le I have addressed most of the comments and will complete the last few this week.

2025-04-20 20:51 UTC, odanrc requested changes

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/Prefetcher.py
> +class IpcpPrefetcher(QueuedPrefetcher):
IPCP is an acronym, so it should be upper case

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.hh
> +class Ipcp : public Queued
Ditto acronym -> uppercase

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.hh
> +/*
Please apply gem5's coding style to this file: https://www.gem5.org/documentation/general_docs/development/coding_style/

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.hh
> +   std::map<Addr, IpEntry> ipcpTable;
include map

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.hh
> +           Addr ipTag = 0;
include base/types.hh

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.hh
> +           std::set<Addr> cacheLineTouched;
include set

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.cc
> +/*
Ditto coding style

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.hh
> +   class CsptEntry
Ditto CSPT acronym -> uppercase

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.hh
> +   class RstEntry
Ditto RST acronym -> uppercase

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.hh
> +   std::map<Addr, RstEntry> RST;
Variable name -> camel case

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.cc
> +  ADD_STAT(pageCross, statistics::units::Count::get(),
Isn't this captured by QueuePref's pfSpanPage?

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.cc
> +        "number of times there was conflict"),
What kind of conflict? Could you add more information to this description?

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.cc
> +    if (ipcpTable[ipIndex].lastVpage != curPage) { //switching it off?
Has this question been solved?

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.cc
> +void
This prefetcher is duplicating some code, as we already have multiple prefetchers implemented in the codebase. As such, could you rework it as a Multi prefetcher?

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.cc
> +    std::cout << "bitsIpIndex: " << bitsIpIndex << std::endl;
Remove mandatory print - we don't want to add more information to the output, unless the user explicitly requests it

2025-04-20 20:51 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.hh
> +   uint64_t RM_SIZE, REGION_SIZE;
camel case

2025-05-01 22:29 UTC, erin-le commented
@AbhishekUoR: Hello, if you have time, could you respond to the comments on this PR as well? Thank you!

2025-05-01 22:45 UTC, AbhishekUoR commented
Oh yes, will do this too over the weekend

2025-05-05 03:46 UTC, AbhishekUoR commented on src/mem/cache/prefetch/ipcp.cc
> +    if (ipcpTable[ipIndex].lastVpage != curPage) { //switching it off?
It's a typo, removing it

2025-05-05 05:06 UTC, AbhishekUoR commented on src/mem/cache/prefetch/ipcp.cc
> +    std::cout << "bitsIpIndex: " << bitsIpIndex << std::endl;
@odanrc should I create #define debug for the print or a config param for the extra information?

2025-05-05 05:24 UTC, AbhishekUoR commented
Hey, I am using my laptop, so it is taking more time than usual to compile gem5 and run some tests, but I will be working on this upcoming week and push changes

2025-05-11 12:52 UTC, odanrc commented on src/mem/cache/prefetch/ipcp.cc
> +    std::cout << "bitsIpIndex: " << bitsIpIndex << std::endl;
We usually print debug information using DPRINTF. For example (untested):
`            DPRINTF(HWPrefetch, "bitsIpIndex: %lld\n", bitsIpIndex);`

See other prefetchers for more examples.

2025-06-26 19:42 UTC, erin-le commented
@AbhishekUoR: Hello, could you give an update on the status of this PR? Thank you!

2025-06-27 11:43 UTC, AbhishekUoR commented
I had refactored the code to satisfy syntax requirements. Please give me a week to have a look at it and come back to this PR

2025-07-23 21:33 UTC, erin-le commented
@AbhishekUoR: Hello, could you give another update on the status of this PR?

2025-08-28 21:14 UTC, erin-le commented
@AbhishekUoR: Hello, do you have any new updates on the status of this PR?

2026-04-14 22:05 UTC, erin-le commented
This PR is being closed for inactivity. If you'd like to continue working on it, however, please feel free to reopen it. Thank you!

2026-04-14 22:05 UTC, closed without merging