mem-cache: Implementation of SMS prefetcher
gem5/gem5 pull request #1454
Opened 2024-08-12 18:03 UTC by AbhishekUoR

This PR adds the SMS prefetcher described in [this ](https://web.eecs.umich.edu/~twenisch/papers/isca06.pdf) paper.

On branch sms
Changes to be committed:
modified: src/mem/cache/prefetch/Prefetcher.py
modified: src/mem/cache/prefetch/SConscript
new file: src/mem/cache/prefetch/sms.cc
new file: src/mem/cache/prefetch/sms.hh

Change-Id: I68d3bb6cf07385177d0f776fb958f652cfc41489

2024-08-15 18:32 UTC, ivanaamit commented
@AbhishekUoR, the tests aren't running for this PR. We believe there's a bug with GitHub that occurs when a PR is initially created on the stable branch and then later changed to develop—GitHub doesn't seem to handle that well. I'll try closing and reopening the PR, but if that doesn't trigger the tests, I suggest you close this PR and open a new one with the same changes, targeting the develop branch instead of stable. Thank you for understanding.

2024-08-19 13:08 UTC, giactra requested changes
Hi @AbhishekUoR thanks for this contribution!

So far I have coding style comments you can start address if you want. I will review the functionality sometime this week

2024-08-19 13:08 UTC, giactra commented on src/mem/cache/prefetch/sms.cc
> +        AGT.clear();
Nit: 4 whitespaces instead of 8

2024-08-19 13:08 UTC, giactra commented on src/mem/cache/prefetch/sms.cc
> +    Addr regionBase = roundDown(info.addr, Region_Size);
Local variables use snake case (region_base)

2024-08-19 13:08 UTC, giactra commented on src/mem/cache/prefetch/sms.cc
> +}
Nit, newline between two methods

2024-08-19 13:08 UTC, giactra commented on src/mem/cache/prefetch/sms.cc
> +    Addr regionBase = roundDown(blk_addr, Region_Size);
Ditto

2024-08-19 13:08 UTC, giactra commented on src/mem/cache/prefetch/sms.cc
> +            Addr prefAddr = blockAddress(regionBase + (*it));
Ditto

2024-08-19 13:08 UTC, giactra commented on src/mem/cache/prefetch/sms.cc
> +        for (std::set<Addr>::iterator it = AGT[regionBase].begin();
Nit, consider using auto

2024-08-19 13:08 UTC, giactra commented on src/mem/cache/prefetch/sms.cc
> +    else if (FT.find(regionBase) != FT.end()) {
This should be

    } else if () {

2024-08-19 13:08 UTC, giactra commented on src/mem/cache/prefetch/sms.cc
> +    else {
Ditto

2024-08-27 09:58 UTC, giactra commented
Hi @AbhishekUoR, thanks for addressing my comments When reviewing the functionality I noticed we actually already have a spatial prefetcher implementation which is the [Spatio-Temporal Memory Streaming Prefetcher (STeMS)](https://github.com/gem5/gem5/blob/stable/src/mem/cache/prefetch/spatio_temporal_memory_streaming.hh). Which I presume is building up on SMS adding temporal streaming.
Did you notice that prefetcher implementation in gem5 when you developed SMS?

I believe the two prefetchers should try to reuse as much code as possible. For example the AGT entry definition in the STeMS.

Another comment I have is that I see you hardcoded an LRU replacement policy with a deque. It would also be nice if we could make it configurable with the ReplacementPolicy Param, and to use the AssociativeCache as well.

Please let me know your thoughts

2024-08-27 14:28 UTC, AbhishekUoR commented
Hello @giactra, I initially tried using STeMS as SMS by disabling the TEMS component, but I found that they differ in how they learn patterns. Another reason for keeping SMS as a separate prefetcher is that ARM cores specifically use SMS and GSMS (for larger pages). 

I chose not to use the STeMS infrastructure to develop independent code that I can test without worrying about issues related to associative set implementations, such as those mentioned here: https://gem5-review.googlesource.com/c/public/gem5/+/37597. 

I agree with the idea of using a replacement policy parameter, which I may consider for future changes to SMS. Currently, I am focusing on implementing other prefetcher-related changes and bug fixes in gem5.

2024-08-27 17:13 UTC, giactra commented
> Hello @giactra, I initially tried using STeMS as SMS by disabling the TEMS component, but I found that they differ in how they learn patterns.

I didn't look into STeMS, but I was not proposing for you to tweak it to make it work like SMS, rather to extract the common code and use it as a base for both (if it is not the algorithm I believe there *might* still be chance to reuse some data structures). Anyway it is not a big deal and the amount of lines we save is probably trivial

> 
> I chose not to use the STeMS infrastructure to develop independent code that I can test without worrying about issues related to associative set implementations, such as those mentioned here: https://gem5-review.googlesource.com/c/public/gem5/+/37597.
> 

I looked into the commit. I don't see anything functionally wrong in the indexing policy implementation as it is. Rather I agree the current interface makes its usage very weird for tables (instead of caches) because of the size/entry_size different meaning. But setting the (entry_size=1) and (size = assoc) effectively makes it work as a fully associative indexing policy which is what you are hardcoding in this PR
You can see this in the BaseIndexingPolicy constructor

https://github.com/gem5/gem5/blob/stable/src/mem/cache/tags/indexing_policies/base.cc#L60C1-L60C48

      numSets(p.size / (p.entry_size * assoc)),
      setShift(floorLog2(p.entry_size)), setMask(numSets - 1), sets(numSets),

Becomes

      numSets(1),
      setShift(0), setMask(0), sets(1),


Anyway I don't want this to be a blocker and I'd rather have this contribution merged rather than forcing you to reuse existing code.
As you are likely running some experiments to check the performance implementation of these prefetchers, you are probably the best person to make the proposed changes while ensuring there is no performance regression

2024-08-27 17:14 UTC, giactra commented on src/mem/cache/prefetch/Prefetcher.py
> +    ft_size = Param.Unsigned(64, "Size of Filter and Active generation table")
From the paper it looks like the AGT is split into a filter table and an accumulation table.
Shall we just call it agt_size? And amen the comment accordingly:

"Size of Filter and Accumulation Table"

2024-08-27 17:14 UTC, giactra commented on src/mem/cache/prefetch/sms.hh
> +    std::map< Addr, std::pair<Addr,Addr> > AGTPC;
Isn't this the Accumulation Table? (Which is part of the AGT together with the FT?)
Also I would consider having a single map like

```
struct AccumulationTableEntry
{
    Addr pc;
    Addr offset;
    std::set<Addr> pattern;
};
std::map<Addr, AccumulationTableEntry> accumulationTable;
```

Instead of having two different maps with the need of storing the same key twice

2024-08-27 17:14 UTC, giactra commented on src/mem/cache/prefetch/sms.hh
> +    const Addr Region_Size; //= 4096;
I would remove the comment here which will change if someone tweaks the parameters.
Also from a coding style perspective I would consider:
```

    const int MaxContexts;
    const uint64_t MaxPHTSize;
    const Addr RegionSize;
```

2024-08-27 17:14 UTC, giactra commented on src/mem/cache/prefetch/sms.cc
> +        for (std::set<Addr>::iterator it = AGT[regionBase].begin();
This still needs some resolving

2024-10-04 14:51 UTC, Harshil2107 commented
Hi @AbhishekUoR and @Setu-Gupta,

Thank you for your contribution! Could you please update us on the status of this PR? I noticed that PRs #1461, #1454, and #1441 seem to be related and add prefetchers. It would be helpful if you could create a discussion post to track the status of these PRs and inform the community about the changes. Additionally, we have a gem5 developer's meeting next Thursday, October 10th. It would be great if you could join us to discuss these updates.

2024-10-18 09:18 UTC, giactra commented
Hi @AbhishekUoR, do you think you will have some time to review my change requests?
If not, as I believe changes are minimal, we can consider merging this as is and we will update the changes ourselves with a separate PR. Let me know what you think about it

2024-10-18 09:34 UTC, AbhishekUoR commented
Hello,

Thank you for making the changes. I reviewed them and they look good.

Thanks,
Abhishek Singh


Remember "Chance favors the prepared mind."(Pasteur)


On Fri, Oct 18, 2024 at 2:18 AM Giacomo Travaglini ***@***.***>
wrote:

> Hi @AbhishekUoR <https://github.com/AbhishekUoR>, do you think you will
> have some time to review my change requests?
> If not, as I believe changes are minimal, we can consider merging this as
> is and we will update the changes ourselves with a separate PR. Let me know
> what you think about it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gem5/gem5/pull/1454#issuecomment-2421938878>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG6MWRM5DKVZNCSY3SWSPNTZ4DG6LAVCNFSM6AAAAABMMVIIX2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMRRHEZTQOBXHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-18 17:15 UTC, giactra approved these changes

2024-10-18 17:15 UTC, merged