stdlib: Refactor pre-inst
gem5/gem5 pull request #1497
Opened 2024-08-22 12:51 UTC by BobbyRBruce

2024-08-22 12:52 UTC, BobbyRBruce commented
((Note: This is still a draft but I wanted to run the tests so have made it "ready for review" purely for this reason)).

2024-09-23 12:14 UTC, BobbyRBruce commented
@mahyarsamani : Is this ok with you?

2024-10-02 22:55 UTC, powerjg reviewed
A couple of small things below. I pushed a commit to fix these things.

2024-10-02 22:55 UTC, powerjg commented on src/python/gem5/components/boards/arm_board.py
> +    def _pre_instantiate(self, full_system: Optional[bool]) -> None:
I don't think `full_system` is "optional" here since it doesn't have a default.

2024-10-02 22:55 UTC, powerjg commented on src/python/gem5/components/boards/riscv_board.py
> +    def _pre_instantiate(self, full_system: Optional[bool]):
I don't think `full_system` is "optional" here since it doesn't have a default.

2024-10-02 22:55 UTC, powerjg commented on src/python/gem5/prebuilt/riscvmatched/riscvmatched_board.py
> +    def _pre_instantiate(self, full_system: Optional[bool]) -> None:
I don't think `full_system` is "optional" here since it doesn't have a default.

2024-10-02 22:55 UTC, powerjg commented on src/python/gem5/components/boards/abstract_board.py
> +        self.get_processor()._pre_instantiate(root)
Let's go ahead and add this for the `cache_hierarchy` and `memory_system`. I need the cache hierarchy to get the power model example in the bootcamp to work.

2024-10-03 00:06 UTC, powerjg commented
Apologies for messing up anything with the force push. I was trying to make your life easier, but pre-commit is broken on my system after upgrading to 24.04.

2024-10-04 18:26 UTC, BobbyRBruce commented on src/python/gem5/components/boards/abstract_board.py
> +        self.get_processor()._pre_instantiate(root)
Unless I'm very confused I believe I already have. Perhaps you were looking at an old commit? The next two lines call the cache hierarchy and memory system pre_instantiate functions

2024-10-04 18:41 UTC, BobbyRBruce commented on src/python/gem5/components/boards/abstract_board.py
> +        self.get_processor()._pre_instantiate(root)
Disregard, that... I was confused. I think I deleted some god reverting your changes. i'll add these

2024-10-04 19:02 UTC, BobbyRBruce reviewed
@powerjg : I take it I can remove the last commit in this chain?  https://github.com/gem5/gem5/pull/1497/commits/14e12907346e4e9132c7bf969c0634f8115e5c2c. It's only purpose was to demo this stuff to Mayhar. I'm not sure it's actually useful

2024-10-04 19:03 UTC, BobbyRBruce commented on src/python/gem5/components/boards/abstract_board.py
> +        self.get_processor()._pre_instantiate(root)
Done

2024-10-04 19:38 UTC, powerjg commented
> @powerjg : I take it I can remove the last commit in this chain? https://github.com/gem5/gem5/commit/14e12907346e4e9132c7bf969c0634f8115e5c2c. It's only purpose was to demo this stuff to Mayhar. I'm not sure it's actually useful

It's up to you. We can remove it and let Mahyar push a change if he thinks it's important.

2024-10-04 19:41 UTC, powerjg reviewed
One little thing. Sorry if I made things harder for you by adding that commit.

2024-10-04 19:41 UTC, powerjg commented on src/python/gem5/components/memory/abstract_memory_system.py
> +        """Called to set up anything needed before ``m5.instantiate``."""
I think this should be removed.

2024-10-04 21:04 UTC, BobbyRBruce commented on src/python/gem5/components/memory/abstract_memory_system.py
> +        """Called to set up anything needed before ``m5.instantiate``."""
Yeah, that was a mistake. Removed.

2024-10-07 22:30 UTC, powerjg commented
I suggest dropping the branch predictor from this pr and creating another with an example.

2024-10-08 15:16 UTC, powerjg requested changes
The branch predictor part of this (most likely) doesn't work. Let's drop that commit and then this can be merged. I would like this merged ASAP because we have other changes that depend on this.

2024-10-09 13:52 UTC, BobbyRBruce commented
> The branch predictor part of this (most likely) doesn't work. Let's drop that commit and then this can be merged. I would like this merged ASAP because we have other changes that depend on this.

I've removed it.

I've added one more patch to this chain. It moves board setup functions to occur after it's decided whether the board is in FS or SE (which is decided based on what set_workload). This allows for easier implementation of boards that support both. All setup functions can call `is_fullsystem` and modify the simulated system accordingly. Very little now happens before the workloads are specified.

2024-10-09 15:30 UTC, powerjg approved these changes

2024-10-10 22:39 UTC, Harshil2107 approved these changes
I tested this change on top of the arm demo board and the boot fs simulation ran successfully. Overall the other changes also look good to me.

2024-10-14 17:12 UTC, merged