util-docker: Add labels to Dockerfiles
gem5/gem5 pull request #1528
Opened 2024-08-30 21:22 UTC by erin-le

This PR adds labels to Dockerfiles. The labels are the source (https://github.com/gem5/gem5), a description, and the license.

Change-Id: I47ce432257641b394efef4958f1474eefe2a11c1

2024-08-30 22:23 UTC, Harshil2107 requested changes

2024-08-30 22:23 UTC, Harshil2107 commented on util/dockerfiles/ubuntu-24.04_all-dependencies/Dockerfile
> +LABEL org.opencontainers.image.description="A Dockerfile to build an Ubuntu 24.04 image with all dependencies for building and using gem5."
```suggestion
LABEL org.opencontainers.image.description="A Dockerfile to build an Ubuntu 24.04 docker image with all dependencies required for building and using gem5."
```

2024-08-30 22:23 UTC, Harshil2107 commented on util/dockerfiles/ubuntu-24.04_min-dependencies/Dockerfile
> +LABEL org.opencontainers.image.description="A Dockerfile to build an Ubuntu 24.04 image with minimal dependencies for building and using gem5."
```suggestion
LABEL org.opencontainers.image.description="A Dockerfile to build an Ubuntu 24.04 docker image with minimal dependencies required for building and using gem5."
```

2024-08-30 22:23 UTC, Harshil2107 commented on util/dockerfiles/ubuntu-22.04_all-dependencies/Dockerfile
> +LABEL org.opencontainers.image.description="A Dockerfile to build an Ubuntu 24.04 image with all dependencies for building and using gem5."
```suggestion
LABEL org.opencontainers.image.description="A Dockerfile to build an Ubuntu 22.04 docker image with all dependencies required for building and using gem5."
```

2024-08-30 22:23 UTC, Harshil2107 commented on util/dockerfiles/gcc-compiler/Dockerfile
> +LABEL org.opencontainers.image.description="A Dockerfile to build an Ubuntu 24.04 image with all dependencies for gem5, with GCC 13."
```suggestion
LABEL org.opencontainers.image.description="A Dockerfile to build an Ubuntu 24.04 docker image with all dependencies for gem5, with GCC 13."
```

2024-08-30 22:23 UTC, Harshil2107 commented on util/dockerfiles/clang-compiler/Dockerfile
> +LABEL org.opencontainers.image.description="A Dockerfile to build an Ubuntu 24.04 image with all dependencies for gem5, with Clang 16."
```suggestion
LABEL org.opencontainers.image.description="A Dockerfile to build an Ubuntu 24.04 docker image with all dependencies for gem5, with Clang 16."
```

2024-08-30 23:06 UTC, Harshil2107 approved these changes
lgtm

2024-09-01 16:51 UTC, powerjg approved these changes

2024-09-01 16:52 UTC, merged