python: infer fs/se mode from workload for boards with both
gem5/gem5 pull request #1579
Opened 2024-09-18 18:40 UTC by erin-le

This commit modifies abstract_board.py so that boards that support both SE and FS mode (have both set_se_binary_workload and set_kernel_disk_workload) can infer which to use based on the workload that is set.

2024-09-18 19:42 UTC, BobbyRBruce requested changes
Thanks for letting me know about this and giving me time to think it through. 

Could you move both `self._self_board()` and `self._setup_memory_ranges()` from the `__init__` and put them both as called above `connect_things` in the `_pre_instantiate` function(i.e., the first things called in that function)?

(Check this works first (I pretty sure  it will though)).

2024-09-18 23:53 UTC, erin-le commented
> Could you move both `self._self_board()` and `self._setup_memory_ranges()` from the `__init__` and put them both as called above `connect_things` in the `_pre_instantiate` function(i.e., the first things called in that function)?
> 

I tried doing this but got the following error:
```
AttributeError: Class StubWorkload has no parameter object_file

At:
  /home/bees/gem5-2nd-worktree/src/python/m5/SimObject.py(922): __setattr__
  /home/bees/gem5-2nd-worktree/src/python/gem5/components/boards/kernel_disk_workload.py(191): set_kernel_disk_workload
  /home/bees/gem5-2nd-worktree/src/python/gem5/components/boards/abstract_board.py(242): set_workload
  ../x86-ubuntu-run-with-kvm-no-perf.py(126): <module>
  /home/bees/gem5-2nd-worktree/src/python/m5/main.py(675): main
```

2024-09-19 01:05 UTC, BobbyRBruce commented
> > Could you move both `self._self_board()` and `self._setup_memory_ranges()` from the `__init__` and put them both as called above `connect_things` in the `_pre_instantiate` function(i.e., the first things called in that function)?
> 
> I tried doing this but got the following error:
> 
> ```
> AttributeError: Class StubWorkload has no parameter object_file
> 
> At:
>   /home/bees/gem5-2nd-worktree/src/python/m5/SimObject.py(922): __setattr__
>   /home/bees/gem5-2nd-worktree/src/python/gem5/components/boards/kernel_disk_workload.py(191): set_kernel_disk_workload
>   /home/bees/gem5-2nd-worktree/src/python/gem5/components/boards/abstract_board.py(242): set_workload
>   ../x86-ubuntu-run-with-kvm-no-perf.py(126): <module>
>   /home/bees/gem5-2nd-worktree/src/python/m5/main.py(675): main
> ```



> > Could you move both `self._self_board()` and `self._setup_memory_ranges()` from the `__init__` and put them both as called above `connect_things` in the `_pre_instantiate` function(i.e., the first things called in that function)?
> 
> I tried doing this but got the following error:
> 
> ```
> AttributeError: Class StubWorkload has no parameter object_file
> 
> At:
>   /home/bees/gem5-2nd-worktree/src/python/m5/SimObject.py(922): __setattr__
>   /home/bees/gem5-2nd-worktree/src/python/gem5/components/boards/kernel_disk_workload.py(191): set_kernel_disk_workload
>   /home/bees/gem5-2nd-worktree/src/python/gem5/components/boards/abstract_board.py(242): set_workload
>   ../x86-ubuntu-run-with-kvm-no-perf.py(126): <module>
>   /home/bees/gem5-2nd-worktree/src/python/m5/main.py(675): main
> ```



> > Could you move both `self._self_board()` and `self._setup_memory_ranges()` from the `__init__` and put them both as called above `connect_things` in the `_pre_instantiate` function(i.e., the first things called in that function)?
> 
> I tried doing this but got the following error:
> 
> ```
> AttributeError: Class StubWorkload has no parameter object_file
> 
> At:
>   /home/bees/gem5-2nd-worktree/src/python/m5/SimObject.py(922): __setattr__
>   /home/bees/gem5-2nd-worktree/src/python/gem5/components/boards/kernel_disk_workload.py(191): set_kernel_disk_workload
>   /home/bees/gem5-2nd-worktree/src/python/gem5/components/boards/abstract_board.py(242): set_workload
>   ../x86-ubuntu-run-with-kvm-no-perf.py(126): <module>
>   /home/bees/gem5-2nd-worktree/src/python/m5/main.py(675): main
> ```

Ok, almost there. Keep this change I suggest but, in addition, move the `self.workload = RiscvBootloaderKernelWorkload()` from your `_setup_board` function and put it in the `_set_fullsystem` function. In `_set_fullsystem` have it so this `self.workload = ...` is run only when `fs=True`. 

Every board (I think) has a similar setup. That is, `self.workload` set in `_setup_board` go through each and do this in each case.

I think once you've done that things will work. If not, can you upload your changes here so I can look at them?

2024-09-21 00:53 UTC, erin-le commented
I was able to get X86Board to work by moving an an additional line from _setup_board into _set_fullsystem. For ArmBoard, RiscvBoard, and RISCVMatchedBoard, it seemed like the majority or entirety of _setup_board would have to be moved into _set_fullsystem before it would work.

2024-10-03 18:18 UTC, closed without merging

2024-10-08 15:13 UTC, BobbyRBruce commented
@erin-le : Why was this closed? Perhaps you mentioned it in person but I don't remember the reason. 

You said this was needed before #1618 was merged so i'm guessing we need to reopen this, right?

2024-10-08 21:59 UTC, erin-le commented
We were trying to get the number of open PRs I had down to zero so I could delete the fork of gem5 I'm currently using and get a new fork directly from gem5/gem5. I closed this PR since the last few messages were just to show you the changes that didn't work.

2024-10-09 13:43 UTC, BobbyRBruce commented
I think last commit in PR #1497 does what we want. Can you look it over and find out if this works and is compatible with the `DemoBoards` or if it's missing anything we may need?