tests: Add Pannotia GPU Tests
gem5/gem5 pull request #1584
Opened 2024-09-20 22:24 UTC by erin-le

This PR adds the Pannotia GPU tests. The input graphs to the binaries were too large to be committed, so they need to be obtained separately. Instructions for how to do so are in README.md.

The GitHub workflow files will need to be modified in order to get the input graphs as well.

2024-09-21 05:50 UTC, mattsinc commented
Thanks for doing this, @erin-le !  Let me know when you want me to review this -- is it WIP?

2024-09-21 17:16 UTC, abmerop commented
This looks fine to me at a quick glance.  Brad says I should not spend time on SE mode GPU stuff so I will defer mostly to @mattsinc  :) . 

Is it possible yet to do the same tests for FS mode?  I believe we have fixed a few issues with KVM on develop that would help but that should probably be discussed in #787 and #456 not here.

2024-09-21 18:59 UTC, BobbyRBruce requested changes

2024-09-21 18:59 UTC, BobbyRBruce commented on tests/gem5/gpu-pannotia-resources/pannotia-bins/color_maxmin.gem5
You accidentally added this directory. At the very least you've got binaries here you're also `wget`ing in the script.

For the datasets, ``wget them too. Binaries and raw data doesn't play nice with git.

2024-09-21 18:59 UTC, BobbyRBruce commented on tests/gem5/gpu/README.md
Looking over this file: little of it makes sense (that main.py command isn't even using the gem5/gpu directory).

2024-09-21 18:59 UTC, BobbyRBruce commented on tests/gem5/gpu/README.md
> +```
We shouldnt be having the user do this. Just have the python script wget the resources was needed.

Let's do this the cheap way: put the wget's (or whatever the python equivalent is) in tests_gpu_pannotia.py. Just have a little part at the top of the file that checks if tests/gem5/resources/pannotia exits, and, if not, creates the directory downloads all the binaries and datafiles into it.

2024-09-21 18:59 UTC, BobbyRBruce commented on .github/workflows/weekly-tests.yaml
> +                  \ "gs://dist.gem5.org/dist/develop/datasets/pannotia/pagerank" \ "gs://dist.gem5.org/dist/develop/datasets/pannotia/sssp" \ .
`gsutil` is mostly a tool for people to interact with their Google Cloud account. I think you need to associate a Google Account. Anyway, I doubt it's installed on our runners and it's really not the tool for the job. If we were to put the download here i'd just recommend `wget`, though I have a suggestion elsewhere in this review that we should put them in "tests_gpu_pannotia.py"

2024-09-24 06:28 UTC, mattsinc commented
Thanks @BobbyRBruce for taking a pass on this.  @erin-le let me know when you'd like me to review it -- or if it's still WIP.

2024-09-24 17:50 UTC, BobbyRBruce approved these changes

2024-09-24 17:52 UTC, erin-le commented
@mattsinc Sorry for the delay; it's ready for review now.

2024-09-26 21:39 UTC, BobbyRBruce approved these changes

2024-09-26 21:39 UTC, merged

2024-09-28 04:51 UTC, mattsinc reviewed
I realize this has already been merged in, but I wanted to add a few comments on things here, @erin-le .  Thanks again for all your hard work and help with this.  I think the main question is if we should run such large input sizes for Pannotia -- the test coverage is more than the smaller ones, but at very large increases in runtime (and running out of memory in some of the cases, as you have documented).

Happy to push a follow-up that makes those changes or let you do so.

2024-09-28 04:51 UTC, mattsinc commented on tests/gem5/gpu/test_gpu_pannotia.py
> +gem5_verify_config(
Nothing wrong with this, but previously we only ran 1 input set per app in the weekly tests.  Running more is fine if we have time/resources, but technically speaking this is not necessary.  Open to discussion though.

2024-09-28 04:51 UTC, mattsinc commented on tests/gem5/gpu/test_gpu_pannotia.py
> +gem5_verify_config(
Previously for color we were running smaller inputs (https://github.com/gem5/gem5/blob/stable/tests/deprecated/weekly.sh#L275) to make the tests complete in a more tractable time.  I believe these test sizes you have will likely run for multiple days.  If that is ok, then fine but just an FYI.

2024-09-28 04:51 UTC, mattsinc commented on tests/gem5/gpu/test_gpu_pannotia.py
> +gem5_verify_config(
same for FW: https://github.com/gem5/gem5/blob/stable/tests/deprecated/weekly.sh#L309

2024-09-28 04:51 UTC, mattsinc commented on tests/gem5/gpu/test_gpu_pannotia.py
> +# This test fails with
I have a fix for this locally but was not aware it was failing for people in public -- I thought it was only for the multi-chiplet support (not on mainline).

Same idea for MIS though about input size: https://github.com/gem5/gem5/blob/stable/tests/deprecated/weekly.sh#L324

2024-09-28 04:51 UTC, mattsinc commented on tests/gem5/gpu/test_gpu_pannotia.py
> +gem5_verify_config(
Same with SSSP: https://github.com/gem5/gem5/blob/stable/tests/deprecated/weekly.sh#L371

2024-10-04 15:42 UTC, mattsinc commented
@erin-le just wanted to make sure you saw these comments

2024-10-04 17:29 UTC, erin-le commented
@mattsinc: The dev team has seen these comments and @Harshil2107 is currently working on making the changes

2024-10-04 18:56 UTC, Harshil2107 commented
@mattsinc: I pushed a PR #1631 with the changes you requested. I am still running the tests locally to see how long they take and if there are any errors.