cpu: fix simInsts and simOps not resetting
gem5/gem5 pull request #1615
Opened 2024-09-27 23:40 UTC by erin-le

This PR fixes the bug where simInsts and simOps don't reset when m5.stats.reset() is called. The stats hostInstRate and hostOpRate are affected by this change as well, as they depend on simInsts and simOps respectively.

This is related to issue 1443 linked [here](https://github.com/gem5/gem5/issues/1443).

2024-09-30 08:11 UTC, giactra requested changes
Hi @erin-le thanks for this fix... I am not a huge fan of caching the previous reset value, as caching lends itself to staleness. However I realise the alternative approach would be to duplicate data structures for the stats/non-stats case. So I am happy to fix it this way. Anyway I have some comments; feel free to review them when you have some time

2024-09-30 08:11 UTC, giactra commented on src/cpu/base.hh
> +        void resetStats() override
Nit:

```
void
resetStats() override
```

2024-09-30 08:11 UTC, giactra commented on src/cpu/base.hh
> +          statistics::Group::resetStats();
requires 4 whitespaces for indentation

2024-09-30 08:11 UTC, giactra commented on src/cpu/base.hh
> +    }
Shouldn't we make this a method of GlobalStats? In this way we avoid extra-stat usage of it

2024-09-30 08:11 UTC, giactra commented on src/cpu/base.hh
> +    }
Ditto

2024-10-01 07:55 UTC, giactra requested changes
Thanks for your changes, I have some other minor comments (mainly coding style related). Would you mind squashing all commits together and force pushing the PR as a single commit?

2024-10-01 07:55 UTC, giactra commented on src/cpu/base.hh
> +        resetStats() override
Nit: would you mind grouping all methods together?

2024-10-01 07:55 UTC, giactra commented on src/cpu/base.hh
> +            return totalNumSimulatedInsts() - (globalStats -> previousInsts);
There shouldn't be whitepaces around the -> operator

2024-10-01 07:55 UTC, giactra commented on src/cpu/base.hh
> +            return totalNumSimulatedOps() - (globalStats -> previousOps);
Ditto

2024-10-01 18:17 UTC, powerjg reviewed
lgtm, after addressing Giacomo's requests

2024-10-03 18:59 UTC, mattsinc commented
While it contributes nothing to the solution discussion, I just wanted to add that some students in my class this semester seemingly had run into the same problem -- so I'm glad @erin-le was already fixing it :)

2024-10-04 08:51 UTC, giactra approved these changes
LGTM, thanks!

2024-10-07 20:47 UTC, powerjg approved these changes

2024-10-10 02:49 UTC, merged

2024-10-10 14:37 UTC, powerjg commented
@erin-le Can you make sure to add something big and bold in the release notes about this change? While this is *fixing* an incorrect behavior, it is making a major change to behavior that people need to be aware of in the next release.