util-docker: Add support for GCC 14
gem5/gem5 pull request #1646
Opened 2024-10-08 22:02 UTC by erin-le

This commit adds gcc 14 to the compiler tests and Dockerfiles.

2024-10-09 09:07 UTC, BobbyRBruce requested changes
I've uploaded the docker image (ghcr.io/gem5/gcc-version-14:latest). 

I have one fix suggestion in this review that should be addressed.

2024-10-09 09:07 UTC, BobbyRBruce commented on .github/workflows/compiler-tests.yaml
> -                image: [gcc-version-13, gcc-version-12, gcc-version-11, gcc-version-10, clang-version-18, clang-version-17, clang-version-16, clang-version-15,
You've accidentally removed `clang-version-15` from the image list.

2024-10-09 09:07 UTC, BobbyRBruce commented on util/dockerfiles/docker-bake.hcl
> +
This all looks good to me but did you build the image locally to mature sure this all works? 

To build this image you'd execute `docker buildx bake gcc-version-14` in the "util/dockerfiles" directory. This does require a machine with docker and some other dependencies installed. If you don't have one already get Mahyar to set you up to user docker on amarillo.

If you had permission to push to the GitHub Container registry you'd run `docker build xbake gcc-version-14 --push`, though setting this up a little annoying so I'll do this right now to save you the hassle. This is more just an "FYI" that these steps are necessary.


**Note:** as i had to build this to upload the image, I've verified it builds just fine :)

2024-10-09 09:07 UTC, BobbyRBruce commented on util/dockerfiles/gcc-compiler/Dockerfile
> +ARG version=14 # Version of GCC to install in this image. Default is 14.
This is fine, but  just so you know, it's not a requirement that the default is the highest supported. I honestly dosn't matter what the default value is. There probably shouldn't be a defaulk as any user wanting to create image from this should know what version they and be blocked by an error when they don't specify it explicitly... but this isn't particularly important right now.

2024-10-09 09:07 UTC, BobbyRBruce commented on .github/workflows/compiler-tests.yaml
In a separate commit or PR, can you can look into doing the same for `clang-version-19`? GCC v14 is the latest gcc version and Clang v19 is the last clang version. It's always nice to save we support the latest if possible.

2024-10-09 18:00 UTC, erin-le commented on .github/workflows/compiler-tests.yaml
> -                image: [gcc-version-13, gcc-version-12, gcc-version-11, gcc-version-10, clang-version-18, clang-version-17, clang-version-16, clang-version-15,
It's still there, it just got moved to the next line by the YAML formatter

2024-10-09 20:22 UTC, BobbyRBruce approved these changes

2024-10-09 20:22 UTC, BobbyRBruce commented on .github/workflows/compiler-tests.yaml
> -                image: [gcc-version-13, gcc-version-12, gcc-version-11, gcc-version-10, clang-version-18, clang-version-17, clang-version-16, clang-version-15,
oh i see! Then this PR is perfect then. ! Thanks @erin-le

2024-10-09 20:46 UTC, erin-le commented
I looked into adding clang-version-19, but since Ubuntu doesn't have a package available for clang-19 yet, I wasn't able to build the image.

2024-10-09 20:46 UTC, powerjg commented
When this is committed, I suggest changing the message to "Add dockerfiles for GCC 14" The current commit message sounds like gem5 is getting support for gcc 14, but IIRC, that's not the case right now.

2024-10-09 20:46 UTC, powerjg approved these changes

2024-10-09 21:54 UTC, BobbyRBruce commented
> I looked into adding clang-version-19, but since Ubuntu doesn't have a package available for clang-19 yet, I wasn't able to build the image.

That's fine, this is often the case. If you can't install it via apt in 24.04 then let's not bother supporting it.

2024-10-09 21:55 UTC, BobbyRBruce commented
> When this is committed, I suggest changing the message to "Add dockerfiles for GCC 14" The current commit message sounds like gem5 is getting support for gcc 14, but IIRC, that's not the case right now.

This PR also adds gcc-14 tests. Doesn't that mean we support GCC 14?

2024-10-09 22:00 UTC, Harshil2107 approved these changes
lgtm

2024-10-09 23:55 UTC, powerjg commented
> This PR also adds gcc-14 tests. Doesn't that mean we support GCC 14?

I'd say "no" #1630 

It adds tests, but do they pass?

2024-10-10 00:22 UTC, BobbyRBruce commented
> > This PR also adds gcc-14 tests. Doesn't that mean we support GCC 14?
> 
> I'd say "no" #1630
> 
> It adds tests, but do they pass?

Unknown until we merge this PR. 

To stop a chicken and problem arising from this conversation, do you want to rename this PR "util-docker: Add compiler tests & dockerfiles for GCC 14"?

2024-10-10 17:17 UTC, merged