arch-riscv: Fix incorrect vector slide instructions and statically filter redundant uops
gem5/gem5 pull request #1712
Opened 2024-10-24 13:48 UTC by 5265325

This PR incorrect vector slide instructions mentioned in #1667.

And statically filter redundant uops for vslideup.vi/vslidedown.vi/vslide1up.vx /vsilde1down.vx/vfslide1up.vf/vfslide1down.vf instructions to improve performance.

Change-Id: I1ba36f216f0bb55372206a94b7f8108acc674f5a

2024-11-01 16:14 UTC, powerjg commented
@saul44203 could you take a look at this? I think you're our resident RVV expert :)

2024-11-11 21:03 UTC, saul44203 requested changes

2024-11-11 21:03 UTC, saul44203 commented on src/arch/riscv/insts/vector.cc
> +    }
I wanted to get to this myself, but I think we can address this here.

The idea was to use an internal register as a dummy destination for the pin micro to create a data dependency with the actual micro instructions that write to the destination register vd. This is to be sure that the mask/tail policy (i.e. keep unchanged or filled with 1s) in the pinned vd is always done before anything is written. The `setDestRegIdx` was missing, so it was actually not creating any dependency at all, but I think we should always create this dependency, so there's no need to do it under a flag.

We should check that all pinned instructions have this register as source too, but this can be done in a separate pr maybe.

2024-11-11 21:03 UTC, saul44203 commented on src/arch/riscv/insts/vector.cc
> +    for (int i = 0; i < _numDestRegs; i++) {
There's no need to apply the policy to the internal reg, so I think we can remove the for loop.

2024-11-11 21:03 UTC, saul44203 commented on src/arch/riscv/isa/formats/vector_arith.isa
> +            setSrcRegIdx(_numSrcRegs++, destRegIdxArr[0]);
I think only slideup instructions should have the old register as source without the tail/mask wrapper (as it always needed), but the rest should use it.

2024-11-11 21:03 UTC, saul44203 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    int microVlmax = vtype_VLMAX(machInst.vtype8, vlen, true);
Minor thing. You already have `micro_vlmax` here.

2024-11-11 21:03 UTC, saul44203 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    int microVlmax = vtype_VLMAX(machInst.vtype8, vlen, true);
Same here.

2024-11-11 21:03 UTC, saul44203 commented on src/arch/riscv/isa/decoder.isa
> +                        int frontLen = vs3WindowRightSlide - vdWindowLeft;
I think this code (and all the similar ones) has some issues. Giving you an example where it fails:

Just changing your example uploaded in #1667 from `vl=64` to `vl=63`:
```
vslidedown_vi v0, v4, 17
vslidedown_vi_micro v0, v5, 17 : SimdMisc :  D=[02020202_02020202_02020202_02020203]
vslidedown_vi_micro v1, v6, 17 : SimdMisc :  D=[03030303_03030303_03030303_03030300]
vslidedown_vi_micro v2, v6, 17 : SimdMisc :  D=[04040404_04040404_04040404_04040000]
vslidedown_vi_micro v3, v7, 17 : SimdMisc :  D=[00000000_00000000_00000000_000000ff]
```
where it should be:
```
vslidedown_vi v0, v4, 17
vslidedown_vi_micro v0, v5, 17 : SimdMisc :  D=[02020202_02020202_02020202_02020203]
vslidedown_vi_micro v1, v6, 17 : SimdMisc :  D=[03030303_03030303_03030303_03030304]
vslidedown_vi_micro v2, v6, 17 : SimdMisc :  D=[04040404_04040404_04040404_04040400]
vslidedown_vi_micro v3, v7, 17 : SimdMisc :  D=[00000000_00000000_00000000_000000ff]
```

Main issue here is the checks that you do with `vl` in the for loops, as this is provoking to not read certain values. I think you can remove them, as we don't really need to check if the reading side surpasses `vl`. This should solve some things but there might be other issues with this 2 source approach (which should be represented in the assembly, as the second source is hidden) and the calculation of the branch which will be taken.

2024-12-06 22:04 UTC, erin-le commented
@5265325 Hello, thank you for your contribution. Could you give an update on the status of this PR on your end?

2024-12-27 17:12 UTC, powerjg commented
@saul44203 when you get a chance can you re-review this?

2025-01-09 09:00 UTC, saul44203 commented on src/arch/riscv/isa/formats/vector_arith.isa
> +            setSrcRegIdx(_numSrcRegs++, destRegIdxArr[0]);
Hi @5265325. Here I meant the use of `tailMaskCondSetSrcWrapper` to create the dependency only when the register tail/mask policy calls for it, but we should only do this for instructions that do not require pinning, If they have pinning the `VPinVdMicroInst` already handles the copying according to the tail/mask policy (that can be overridden with the `hasVdOffset` flag), and we should not put the destination register as source in those cases, as it will cause gem5 to crash when building the dependency graph. 

This is the case with `vslideup.vx`, where the slide micro will be a consumer of the pinning micro as a cause of this code, but then it will also try to put itself as a producer of the same physical register.

So, in summary, I think we have to remove this for the pinning cases, and the others, since they copy directly, should do this using `tailMaskCondSetSrcWrapper`.

2025-01-09 09:00 UTC, saul44203 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    if (copyVs) {
Minor thing, but this isn't necessary in the instructions that don't pin, right? Even if the source and destination registers are the same arch reg, they will rename to different physical registers.

2025-01-09 09:36 UTC, saul44203 requested changes

2025-01-09 09:36 UTC, saul44203 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    }
Minor thing, but this isn't necessary in the instructions that don't pin, right? Even if the source and destination registers are the same arch reg, they will rename to different physical registers.

2025-01-09 09:36 UTC, saul44203 commented on src/arch/riscv/isa/formats/vector_arith.isa
> +        num_src_regs += 1
Hi @5265325. Here I meant the use of `tailMaskCondSetSrcWrapper` to create the dependency only when the register tail/mask policy calls for it, but we should only do this for instructions that do not require pinning, If they have pinning the `VPinVdMicroInst` already handles the copying according to the tail/mask policy (that can be overridden with the `hasVdOffset` flag), and we should not put the destination register as source in those cases, as it will cause gem5 to crash when building the dependency graph. 

This is the case with `vslideup.vx`, where the slide micro will be a consumer of the pinning micro as a cause of this code, but then it will also try to put itself as a producer of the same physical register.

So, in summary, I think we have to remove this for the pinning cases, and the others, since they copy directly, should do this using `tailMaskCondSetSrcWrapper`.

2025-01-13 06:48 UTC, 5265325 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    }
I just want to reduce the redundant uop, so that the uop split closer to the real cpu. Excess uop can affect performance results.

2025-01-13 10:37 UTC, saul44203 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    }
Yeah, I see that, but in this case I meant that we do not need the `VCpyVsMicroInst` at all.

2025-01-15 02:33 UTC, 5265325 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    }
There is still a vslideup scene that needs VCpyVsMicroInst. 
```shell
vsetivli zero, 8, e64, m2, ta, ma
vslideup.vi v1, v0, 2
```
In gem5's renaming logic, the destination register of the first uop is v1, but the source register of the second uop uses the result of the first uop, which is incorrect. So we need to copy v1 to a temporary register before uop split.

2025-01-15 13:12 UTC, saul44203 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    }
I see that would be the case. However, one thing that we missed is that per spec the source and destination register groups of the [slideup instructions cannot overlap](https://github.com/riscvarchive/riscv-v-spec/blob/master/v-spec.adoc#1631-vector-slideup-instructions) , so this should not happen (and maybe we should add this cases as explicit illegal instruction faults in the future). For slidedown it does not say this but spike gives illegal instruction when there's overlap and LMUL>1.

2025-01-26 06:19 UTC, 5265325 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    }
Now the vslide instruction that overlaps will raise an illegal exception.

2025-01-26 07:10 UTC, 5265325 commented on src/arch/riscv/isa/formats/vector_arith.isa
> +        num_src_regs += 1
> VPinVdMicroInst

I'm not quite sure what you mean. It seems to me that VPinVdMicroInst is responsible for deciding whether to keep the old value or write 0xff. And slide micro is responsible for deciding whether to write the new value. Both are necessary.

2025-01-27 12:10 UTC, saul44203 commented on src/arch/riscv/isa/formats/vector_arith.isa
> +        num_src_regs += 1
Yes, it decides whether or not to copy based on the current tail/mask policy. But the thing is that if you use the `VPinVdMicroInst` there's no need to use the `copyOldVd` method (with the `oldDstIdx` as src reg and such) on the actual slide micro instruction. Doing so will produce the crash that I mentioned with `vslideup.vx`.

2025-01-27 13:43 UTC, saul44203 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    }
Sorry for reopening this but what about slidedown instructions? I think we should allow overlap at least when LMUL=1 like spike does. We could also make them work for LMUL>1 if you want, as spec does not say otherwise.

2025-02-05 03:25 UTC, 5265325 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    }
Yes. I check overlap only when LMUL > 1.

2025-02-06 02:57 UTC, 5265325 commented
@saul44203 The rvv-matmul and rvv-reduce test failed in CI. However, they passed in my local testing. when you get a chance could you take a look?

Here are my test commands.
```shell
./build/RISCV/gem5.opt  ./configs/example/gem5_library/riscv-rvv-example.py rvv-matmul --vlen=256
./build/RISCV/gem5.opt  ./configs/example/gem5_library/riscv-rvv-example.py rvv-reduce --vlen=16384
```

2025-02-11 13:46 UTC, saul44203 requested changes

2025-02-11 13:46 UTC, saul44203 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +
Sorry for repeating myself, but this will allow slide up instructions to overlap when LMUL<=1, and spec does not allow this. Only slide down instructions should be allowed to overlap as we talked previously.

Maybe we can filter here with a flag or something?

2025-02-11 13:46 UTC, saul44203 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +                                      true);
Here we will also need the `VCpyVsMicroInst` when there's overlap to avoid the dependency graph crash.

2025-02-11 13:49 UTC, saul44203 commented
> @saul44203 The rvv-matmul and rvv-reduce test failed in CI. However, they passed in my local testing. when you get a chance could you take a look?
> 
> Here are my test commands.
> 
> ```shell
> ./build/RISCV/gem5.opt  ./configs/example/gem5_library/riscv-rvv-example.py rvv-matmul --vlen=256
> ./build/RISCV/gem5.opt  ./configs/example/gem5_library/riscv-rvv-example.py rvv-reduce --vlen=16384
> ```

This I don't understand. They are working well on my side too.

2025-02-14 19:03 UTC, Harshil2107 commented
I have also tested running the CI tests locally in the docker container and they pass. I will take a look into the failing tests but it might be a resource issue with the runners not having enough resources to run the tests.

2025-02-19 08:38 UTC, 5265325 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +                                      true);
Now only num_microops>2 cases require pin micro. VCpyVsMicroInst was moved to VPinVdMicroInst to reduce the number of uops.

2025-02-21 17:17 UTC, saul44203 requested changes
Only a couple of small things. Otherwise lgtm.

2025-02-21 17:17 UTC, saul44203 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +                                      true, overlap, machInst.vs2 + i);
I think here we should use `hasVdOffset=false`.

2025-02-21 17:17 UTC, saul44203 commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    if (slideUp || vtype_vlmul(machInst.vtype8) > 1) {
I think this should be `> 0` if using the `vlmul` (not `LMUL`) since this will sign extend to 1 when `LMUL=2`.

2025-02-25 09:05 UTC, saul44203 approved these changes

2025-02-25 15:52 UTC, powerjg submitted a review, later dismissed

2025-04-18 15:29 UTC, powerjg commented
Quick update on this... I just downloaded this PR and tried to run the commands. When I did, they both resulted in "fail"

```
./build/RISCV/gem5.opt  ./configs/example/gem5_library/riscv-rvv-example.py rvv-matmul --vlen=256
./build/RISCV/gem5.opt  ./configs/example/gem5_library/riscv-rvv-example.py rvv-reduce --vlen=16384
```

```
command line: ./build/RISCV/gem5.opt ./configs/example/gem5_library/riscv-rvv-example.py rvv-reduce --vlen=16384

info: Using default config
warn: Setting the full_system parameter via the Simulator constructor is deprecated and will be removed in future releases of gem5. The board determines if the simulation is full system or not via it's `is_fullsystem` method.
Beginning simulation!
Global frequency set at 1000000000000 ticks per second
warn: No dot file generated. Please install pydot to generate the dot file and pdf.
src/arch/riscv/isa.cc:286: info: RVV enabled, VLEN = 16384 bits, ELEN = 64 bits
src/base/statistics.hh:279: warn: One of the stats is a legacy stat. Legacy stat is a stat that does not belong to any statistics::Group. Legacy stat is deprecated.
board.remote_gdb: Listening for connections on port 7000
src/sim/simulate.cc:200: info: Entering event queue @ 0.  Starting simulation...
src/sim/syscall_emul.cc:97: warn: ignoring syscall set_robust_list(...)
      (further warnings will be suppressed)
src/sim/syscall_emul.hh:1121: warn: readlink() called on '/proc/self/exe' may yield unexpected results in various settings.
      Returning '/home/jlp/.cache/gem5/rvv-reduce'
src/sim/mem_state.cc:448: info: Increasing stack size by one page.
src/sim/syscall_emul.cc:86: warn: ignoring syscall mprotect(...)
src/sim/mem_state.cc:448: info: Increasing stack size by one page.
src/sim/mem_state.cc:448: info: Increasing stack size by one page.
/home/jlp/.cache/gem5/rvv-reduce: fail
```

2025-04-23 15:20 UTC, saul44203 requested changes

2025-04-23 15:20 UTC, saul44203 commented on src/arch/riscv/insts/vector.cc
> +    setDestRegIdx(_numDestRegs++, vecRegClass[VecMemInternalReg0 + _microIdx]);
This interferes with `vcpyvs_v_micro` when both are renaming the same internal reg. Since the pin micro comes after the copy one, the actual instruction's micro that has it as a source will get the renamed reg from this one instead of the copy, which is incorrect.

@powerjg I think we didn't see this happen before because one of the rebases included #1955 and since both `rvv-reduce` and `rvv-matmul` have a reduction those will now fail with the added pinning.

I think we should remove this so the tests pass normally, as this was added as way of enforcing a dependency between pinning and regular micro instructions, but it was preemptive and we could revise this if needed on another pr.

2025-04-23 15:20 UTC, saul44203 commented on src/arch/riscv/isa/formats/vector_arith.isa
> +
This too.

2025-04-25 18:38 UTC, powerjg commented on src/arch/riscv/insts/vector.cc
> +    setDestRegIdx(_numDestRegs++, vecRegClass[VecMemInternalReg0 + _microIdx]);
Sounds like a good solution to me.

2025-05-14 19:25 UTC, erin-le commented
@5265325 Hello, could you respond to the comments on this PR when you get a chance? Thank you!

2025-05-21 16:46 UTC, saul44203 approved these changes
LGTM

2025-05-22 14:48 UTC, powerjg commented
@erin-le can you re-run the tests above to make sure they pass now?

2025-05-22 18:52 UTC, erin-le requested changes
Running `riscv-rvv-example.py` with `rvv-reduce --vlen=16384` and `rvv-matmul --vlen=256` both pass. However, there are numerous lines in this PR that are longer than 79 characters.

2025-05-26 09:18 UTC, 5265325 commented
> Running `riscv-rvv-example.py` with `rvv-reduce --vlen=16384` and `rvv-matmul --vlen=256` both pass. However, there are numerous lines in this PR that are longer than 79 characters.

Now the 80 character limit has been satisfied.

2025-05-27 15:49 UTC, powerjg requested changes
Still has lines >80 char. I know it's annoying..

2025-05-27 15:49 UTC, powerjg commented on src/arch/riscv/insts/vector.cc
> +      ss  << registerName(srcRegIdx(0)) << ", " << registerName(srcRegIdx(1)) << ", " << machInst.vecimm;
Over 80 char

2025-05-27 15:49 UTC, powerjg commented on src/arch/riscv/insts/vector.cc
> +      ss  << registerName(srcRegIdx(1)) << ", " << registerName(srcRegIdx(2)) << ", " << registerName(srcRegIdx(0));
Over 80 char

2025-05-27 15:49 UTC, powerjg commented on src/arch/riscv/isa/formats/vector_arith.isa
> +        return "if (!_machInst.vtype8.vta || (!_machInst.vm && !_machInst.vtype8.vma)) {\n" \
Over 80 char

2025-05-27 15:49 UTC, powerjg commented on src/arch/riscv/isa/formats/vector_arith.isa
> +    src2_reg_id = "vecRegClass[(_copyVs ? VecMemInternalReg0 : _machInst.vs2) + vs2Idx]"
Over 80 char

2025-05-28 15:57 UTC, powerjg commented on src/arch/riscv/insts/vector.cc
> +      ss  << registerName(srcRegIdx(0)) << ", " << registerName(srcRegIdx(1)) << ", " << machInst.vecimm;
This still is over 80 characters. Maybe there is a force-push/rebase issue here?

2025-05-28 15:58 UTC, powerjg commented
@BobbyRBruce we should get this on the staging branch if at all possible. Apologies for missing this on the milestone.

2025-05-28 17:59 UTC, BobbyRBruce commented
> @BobbyRBruce we should get this on the staging branch if at all possible. Apologies for missing this on the milestone.

Ack. Will cherry-pick to `staging` when merged into `develop`

2025-05-28 18:53 UTC, erin-le requested changes
There are a few more lines that are longer than 80 characters. Thanks for your patience with the review process!

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +        microop = new VPinVdMicroInst(machInst, i, std::max(i, 1), elen, vlen, true,
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    uint32_t vsIdxMax = (1 << std::max<int64_t>(0, vtype_vlmul(_machInst.vtype8))) - 1;
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +                _machInst, micro_vl, micro_idx++, i, vs2Idx, vs3Idx, _elen, _vlen,
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    uint32_t vsIdxMax = (1 << std::max<int64_t>(0, vtype_vlmul(_machInst.vtype8))) - 1;
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +            bool copyAll = vs3WindowLeft >= vdWindowLeft && vs3WindowLeft < vdWindowRight;
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +                    _machInst, micro_vl, micro_idx++, i, vs2Idx, vs3Idx, _elen, _vlen,
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +        microop = new VPinVdMicroInst(machInst, i, std::max(num_microops-i-1, 1), elen, vlen,
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    uint32_t vsIdxMax = (1 << std::max<int64_t>(0, vtype_vlmul(_machInst.vtype8))) - 1;
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +                _machInst, micro_vl, micro_idx++, i, vs2Idx, vs3Idx, _elen, _vlen,
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +    uint32_t vsIdxMax = (1 << std::max<int64_t>(0, vtype_vlmul(_machInst.vtype8))) - 1;
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +            bool copyFrontFromVs2 = vs3WindowLeftSlide > vdWindowLeft && vs3WindowLeftSlide <= vdWindowRight;
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +            bool copyFrontFromVs3 = lastUopForVd && vs3WindowRightSlide > vdWindowLeft && vs3WindowRightSlide <= vdWindowRight;
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +                    false, lastUopForVd, i == (num_microops - 1) || micro_vl < micro_vlmax);
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +                    _machInst, micro_vl, micro_idx++, i, vs2Idx, vs3Idx, _elen, _vlen,
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +            bool needZeroTail = lastUopForVd && vs3WindowRightSlide <= vdWindowLeft;
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +            return std::make_shared<IllegalInstFault>("Regs overlap is not allowed for vslideup", machInst);
Over 80 chars

2025-05-28 18:53 UTC, erin-le commented on src/arch/riscv/isa/templates/vector_arith.isa
> +            return std::make_shared<IllegalInstFault>("Regs overlap is not allowed for vslidedown when lmul > 1", machInst);
Over 80 chars

2025-05-29 02:52 UTC, 5265325 commented
@powerjg @erin-le Thanks. I have used precommit to check the character length. The length requirement should now be met.

2025-05-29 09:01 UTC, BobbyRBruce commented
You had a merge conflict in "src/arch/riscv/isa/templates/vector_arith.isa" due to changes introduced in PR #1387 (it was just merged yesterday morning so a new addition). I took the liberty of fixing the conflict by simply preserving the changes introduced in #1387 along side yours but _please_ double check to ensure I haven't done anything stupid here.

2025-05-29 09:36 UTC, 5265325 commented
> You had a merge conflict in "src/arch/riscv/isa/templates/vector_arith.isa" due to changes introduced in PR #1387 (it was just merged yesterday morning so a new addition). I took the liberty of fixing the conflict by simply preserving the changes introduced in #1387 along side yours but _please_ double check to ensure I haven't done anything stupid here.

LGTM

2025-05-29 13:31 UTC, powerjg approved these changes
Thanks for the updates!

2025-05-31 08:38 UTC, merged