ext: Fix typo in README.md
gem5/gem5 pull request #1763
Opened 2024-11-06 09:59 UTC by SimonLammer

2024-11-06 17:23 UTC, ivanaamit approved these changes

2024-11-06 17:25 UTC, ivanaamit requested changes
Thank you for fixing this. Could you please target develop branch instead of stable? Thank you.

2024-11-06 17:34 UTC, powerjg commented
Thanks for the contribution! In addition to targeting develop, can you change the tag to "misc:"? Ext is for external projects

2024-11-09 14:48 UTC, SimonLammer commented
@ivanaamit @powerjg done

2024-11-10 08:15 UTC, ivanaamit approved these changes

2024-11-11 18:03 UTC, merged