Remove cyclic dependency of SimObjects and probes
gem5/gem5 pull request #1787
Opened 2024-11-18 01:05 UTC by odanrc

Remove SimObject pointer from ProbeManager, as it is only used to get the SimObject's name for improved debugging messages. This adds an unnecessary dependency, and since the name should not change throughout execution, it can be stored on construction instead by inheriting from the Named class.

Finally, we remove the ProbeListenerObject class, which is only supposed to act as a wrapper for SimObjects whose probe manager is the one of another object. This class was adding a cyclic dependency that complicated creating unit tests for SimObjects, and had little benefits. Thus, we instead explicitly call the object's manager on the code that needs it and remove the class.

2024-11-18 12:43 UTC, giactra commented
Just wanted to flag this PR is conflicting with https://github.com/gem5/gem5/pull/1439

It would be nice if we could harmonize between them

2024-11-18 17:55 UTC, BobbyRBruce commented
@studyztp : You're my expert on probes. Can you review this change and #1439?

2024-11-18 17:59 UTC, studyztp commented
> @studyztp : You're my expert on probes. Can you review this change and #1439?

Sure, I'll review them. For #1439, I was waiting for the update on the PR.

2024-12-07 16:56 UTC, odanrc commented
Dropped the commit removing the probe listener object and instead moved it to a separate file. This removed the dependency, and made the PR backwards compatible and trivial. Please review when possible, as this and #1785 are the last steps required to allow unit testing SimObjects.

2025-01-06 18:13 UTC, powerjg approved these changes

2025-01-06 18:33 UTC, erin-le commented
@studyztp: If you have the time, could you give this PR a review? Thank you!

2025-01-06 21:52 UTC, studyztp requested changes
Thank you for your contribution! I carefully reviewed the changed files, and they look good to me. There is just one small issue with one of the changes involving the include file.

2025-01-06 21:52 UTC, studyztp commented on src/cpu/simple/probes/looppoint_analysis.hh
>  #include "cpu/simple_thread.hh"
The ```#include "cpu/probes/pc_count_pair.hh"``` is still needed for the PcCountPair type.

2025-01-06 21:56 UTC, odanrc commented on src/cpu/simple/probes/looppoint_analysis.hh
>  #include "cpu/simple_thread.hh"
There is no instance of PcCountPair in this file

2025-01-06 23:38 UTC, studyztp commented on src/cpu/simple/probes/looppoint_analysis.hh
>  #include "cpu/simple_thread.hh"
You're right. Sorry about this.

2025-01-06 23:39 UTC, studyztp approved these changes

2025-01-07 00:17 UTC, BobbyRBruce approved these changes

2025-01-13 18:14 UTC, merged