arch-riscv: fix tlb stats in timming mode
gem5/gem5 pull request #1832
Opened 2024-12-03 07:55 UTC by clemdiep-heig

The previous #484 issue reported a bug where the TLB stats on RISC-V were incremented twice on misses by calling the `lookup` function twice with hidden argument set to `false`. The fix is only applied on atomic mode as the `translation` argument of `doTranslate` will not be `nullptr` in timing mode.

In that case, if the TLB lookup miss, the `doTranslate` function will start the walker and then return without doing anything more. Then later, when the pagetable walker found the corresponding PTE, it will insert it and call `translateWithTLB`. This function then call `lookup` again which will hit in any case (and crash if not due to the following
assert), but the hit count is incremented here too. 

This commit fix by setting the `hidden` argument of `lookup` to true.

2024-12-04 23:50 UTC, powerjg requested changes
Thanks for the contribution!

I think this looks like a good fix. However, now the name `translateWithTLB` is misleading. I think we should call it `hiddenTranslateWithTLB` if the access is always hidden.

If you can make this change by tomorrow, we will merge this into the upcoming 24.1 release. Thanks!

2024-12-05 08:04 UTC, clemdiep commented
Thanks for you review!

I did the change at all necessary places and rebased on top of develop, so it should be good to go.

2024-12-05 15:34 UTC, powerjg approved these changes
Thanks for the updates!

2024-12-06 19:25 UTC, BobbyRBruce approved these changes

2024-12-06 19:25 UTC, merged