Speculative update for TAGE-SC-L
gem5/gem5 pull request #1854
Opened 2024-12-12 14:17 UTC by dhschall

_Note: This PR still depends on #499_

As pointed out in [this ](https://github.com/orgs/gem5/discussions/1341) recent discussion. TAGE-SC-L does not support speculative updates.
This commit adds initial support for speculative updates in TAGE and the statistical corrector.
I have tested it on three different workloads and compared it against the original code from Seznec obtained from the branch prediction championship. It's pretty close, but I probably have not caught all corner cases 

The last commit in this PR contains the reference code. Before merging, I'll remove this commit, but I kept it for others to try with additional workloads.
Note: To correlate the results against the original code, the `instShiftAmt` of the branch predictor must be set to 0.

The plot shows the reference code with the atomic core (It only works with the atomic core as the original code does not support speculative updates) and the gem5 implementation with the atomic core.
Furthermore, with the O3 core with and without speculative updates.

TODO: Add graph

2025-04-23 11:44 UTC, aperais commented
Hi David, my student and I have been reviewing some parts of the BP code, and I was wondering if this PR should also fix the broken global history restore on flushes not caused by a branch.

Basically what happens if you get e.g. a memory ordering flush is that you get into the following call stack (bottom is older), and assuming you have a TAGE somewhere.

TAGE::squash(ThreadID tid, void * &bp_history) -> Deletes the history object and that's it  (https://github.com/gem5/gem5/blob/b9da2bfe1e21f6efa2730edd4e80e58c5d965458/src/cpu/pred/tage.cc#L102C1-L102C47)
BPredUnit::squashHistory(ThreadID tid, PredictorHistory* &history) -> Calls the "real" squash of the BP implementation (https://github.com/gem5/gem5/blob/b9da2bfe1e21f6efa2730edd4e80e58c5d965458/src/cpu/pred/bpred_unit.cc#L419)
BPredUnit::squash(const InstSeqNum &squashed_sn, ThreadID tid) -> Iterates through younger PredictorHistory (https://github.com/gem5/gem5/blob/b9da2bfe1e21f6efa2730edd4e80e58c5d965458/src/cpu/pred/bpred_unit.cc#L393)

Consider this case :

[sn:10] is a load that executed OoO with a store, flushes
[sn:20] is a cond branch that speculatively updated TAGE histories

The way it is handled now, the PredictorHistory for [sn:20] is just popped and the object deleted, but the histories are not restored. One way I have fixed it locally is to add a function restoreHistory() that copies whatever is in the TAGEBase::BranchInfo back to the TAGE objects and I call this function in TAGE::squash(ThreadID tid, void * &bp_history). This is a bit dumb because I restore n times even though I should just restore for the oldest younger branch.

Do you think this could be baked into this PR since this is the "fix TAGE PR", or another PR ? I think it's a fairly big problem since the more non branch flushes you have the worse it gets. Intuitively, larger ROB would have more memory ordering flushes and suffer more.

2025-04-25 12:05 UTC, rjc-arch requested changes
Hi David,

Thanks for this update! It's all looking good.

I've added some comments below. Most are just small tweaks that you might consider changing (if you agree) since you will be pushing a new version to remove the "TAGE-SC-L reference" commit anyway.

A couple of the comments probably do deserve a closer look, though they might not be problems (depending on whether my understanding is correct or not).

Note: I haven't reviewed the "TAGE-SC-L reference" commit, as this will be removed before merging.

Thanks again for your hard work!

2025-04-25 12:05 UTC, rjc-arch commented on src/cpu/pred/BranchPredictor.py
> +        Parent.instShiftAmt, "Number of bits to shift instructions by"
Optional: it might be worth adding a quick note to this help string to explain the reason. e.g. "Used to shift out always-zero bits in fixed size encodings." 
Your explanation of the parameter in the commit comment was very useful, and it would be nice to preserve that in the code, either as a comment or a help string.

2025-04-25 12:05 UTC, rjc-arch commented on src/cpu/pred/statistical_corrector.hh
> +            Addr shifted_pc = pc;
Should this `pc` be shifted by `instShiftAmt`? If not, then the temporary `shifted_pc` could be removed.

2025-04-25 12:05 UTC, rjc-arch commented on src/cpu/pred/BranchPredictor.py
> +    )
Another option would be to check for a null statistical corrector SimObject in the configuration. Are there situations where a SC would be created but not enabled?

Just an idea; I'd be happy to leave this as-is.

2025-04-25 12:05 UTC, rjc-arch commented on src/cpu/pred/ltage.hh
> +    virtual void squash(ThreadID tid, void * &bp_history) override;
Nit: No need to specify both `virtual` and `override` here. 
(C.128 of the C++ Core Guidelines recommends using only one of these qualifiers, for clarity.)

2025-04-25 12:05 UTC, rjc-arch commented on src/cpu/pred/statistical_corrector.cc
> +    if (speculative != speculativeHistUpdate) {
Should this test be `speculative && !speculativeHistUpdate`?
The current test will not update the histories for non-speculative updates if `speculativeHistUpdate` is true. 
Is that the desired behaviour?
(There are a couple of other instances of this test in the code, one which pre-dates your changes.)

2025-04-25 12:05 UTC, rjc-arch commented on src/cpu/pred/statistical_corrector.hh
> +        int64_t imliCount;
Optional: Would it be possible to have a comment on this member? The meanings of some of the members are not very obvious.

2025-04-25 12:05 UTC, rjc-arch commented on src/cpu/pred/statistical_corrector.hh
> +        bool taken,Addr target, int64_t phist);
Nit: missing space after comma.

2025-04-25 12:05 UTC, rjc-arch commented on src/cpu/pred/tage.hh
> +    virtual void updateHistories(ThreadID tid, Addr pc, bool uncond,
Nit: no need for both `virtual` and `override` here.

2025-04-25 12:05 UTC, rjc-arch commented on src/cpu/pred/tage_base.cc
>      if (speculative != speculativeHistUpdate) {
See comment above about this conditional.

2025-04-25 12:05 UTC, rjc-arch commented on src/cpu/pred/tage_base.hh
> +    int calcNewPathHist(ThreadID tid, Addr pc, int old_phist) const;
Nit: the third parameter is named `old_phist` here, and `phist` in the definition. It might be clearer to make them the same.

2025-04-25 12:05 UTC, rjc-arch commented on src/cpu/pred/statistical_corrector.cc
> +    return (((((shifted_pc ^(shifted_pc >>2))<<1) ^ (bi->lowConf & bias)) <<1)
Optional: although it's pre-existing code, it might be nice to update the formatting of these expressions (here and a few below) to conform to the gem5 style guidelines while you are making the changes. e.g. binary operators should have a space either side, etc.

2025-04-25 12:08 UTC, rjc-arch commented
In addition to the above review, I have run some comprehensive performance regressions on this PR and have reviewed the results with @dhschall. We are satisfied that the PR is working as expected, and that the updates to the TAGE-SC-L model now match the reference implementation to a reasonable error margin.

2025-04-25 19:22 UTC, dhschall commented on src/cpu/pred/BranchPredictor.py
> +    )
Good idea. Let me try that

2025-04-25 19:22 UTC, dhschall commented on src/cpu/pred/statistical_corrector.hh
> +            Addr shifted_pc = pc;
Good catch

2025-04-28 05:56 UTC, dhschall commented on src/cpu/pred/BranchPredictor.py
> +        Parent.instShiftAmt, "Number of bits to shift instructions by"
See above

2025-04-28 05:59 UTC, dhschall commented on src/cpu/pred/BranchPredictor.py
> +    speculativeHistUpdate = Param.Bool(
Added the speculative history update parameter in the base class. This allows multiple subcomponents to inherit that parameter (e.g. tage and statistical corrector)

2025-04-28 06:47 UTC, dhschall commented on src/cpu/pred/statistical_corrector.cc
> +    if (speculative != speculativeHistUpdate) {
The history update function is called twice. After making a prediction (`speculative=true`) and at commit (`speculative=false`). Depending on the configuration one update should be skipped.
E.g. if `speculativeHistUpdate` is set to True only the update at prediction should happened and the update at commit should be skipped.
I.e. The update should only happen if `speculative == speculativeHistUpdate`.

2025-05-01 19:15 UTC, rjc-arch requested changes
Hi @dhschall,

Thanks for all the updates! I think this PR is almost ready to go now. I've pointed out a couple more minor issues below that you might consider, but I'd be happy to approve this as it stands now.

Let me know if you'd like to address any of the comments or not, and then I'll do the final approval.

2025-05-01 19:15 UTC, rjc-arch commented on src/cpu/pred/BranchPredictor.py
> +        "(Arm,RISC-V) to shift the FULL PC by ``n` bits (e.g. 2 for 4 byte "
Thanks for this update!
Nit: there's a slight error in the formatting of `` `n` `` here (doubled backtick).

2025-05-01 19:15 UTC, rjc-arch commented on src/cpu/pred/BranchPredictor.py
> +        2,
Should the default here be `0` or `2`?
- The case for `0`: it would degrade performance slightly for Arm and RISC-V, but using `instShiftAmt=0` for Arm/RISC-V by mistake might be less detrimental than using `instShiftAmt=2` for x86 by mistake.

I don't have a strong opinion on this, but it would be worth considering.

2025-05-01 19:15 UTC, rjc-arch commented on src/cpu/pred/BranchPredictor.py
> +        Parent.instShiftAmt, "Number of bits to shift instructions by"
Thank you - that looks great!

2025-05-01 19:15 UTC, rjc-arch commented on src/cpu/pred/BranchPredictor.py
> +    speculativeHistUpdate = Param.Bool(
This seems like a good improvement!

2025-05-01 19:15 UTC, rjc-arch commented on src/cpu/pred/BranchPredictor.py
> +    speculativeHistUpdate = True
Is this still needed, now we have the `speculativeHistUpdate` `Param` in the `BranchPredictor` base class?

2025-05-01 19:15 UTC, rjc-arch commented on src/cpu/pred/tage_sc_l.cc
> +    if (useSC) {
Nit: this reference to `useSC` remains from an old version.
It gets removed in the next commit of the PR, but could cause problems in the future if cherry-picking patches or using `git bisect`. 
I'll leave it up to you if you think it's worth fixing or not.

2025-05-01 19:15 UTC, rjc-arch commented on src/cpu/pred/statistical_corrector.cc
> +    if (speculative != speculativeHistUpdate) {
👍 Thanks for clarifying this, David.

2025-05-01 19:15 UTC, rjc-arch commented on src/cpu/pred/statistical_corrector.hh
> +            Addr shifted_pc = pc >> instShiftAmt;
Nit: this fix looks like it's in the wrong commit. 
Again, not a problem unless someone tries cherry-picking/`git bisect`ing in the future, so I'll let you decide if it's worth fixing or not.

2025-05-01 21:36 UTC, dhschall commented on src/cpu/pred/BranchPredictor.py
> +    speculativeHistUpdate = True
I think yes, because in the base I use speculative history = Falso but TAGE supports speculative updates.
However, I think you are right that it should be True by default.
Also, I've realized that now I also have to move the configurations for the multiperspective perception predictors to the BranchPredictor base class.

2025-05-01 21:42 UTC, dhschall commented on src/cpu/pred/statistical_corrector.hh
> +            Addr shifted_pc = pc >> instShiftAmt;
Thanks for the catch. I've moved it

2025-05-01 21:49 UTC, dhschall commented on src/cpu/pred/tage_sc_l.cc
> +    if (useSC) {
Good point thanks

2025-05-01 21:51 UTC, dhschall commented on src/cpu/pred/BranchPredictor.py
> +        2,
Good point. Will make it 0

2025-05-01 22:07 UTC, dhschall commented
Thanks for the feedback. I've addressed your comments. Let me know if I missed something else.

2025-05-02 10:42 UTC, rjc-arch approved these changes
Thank you for the latest round of updates, @dhschall. 

I think this one is ready to merge now! Thanks for all your hard work!

2025-05-06 09:14 UTC, andysan approved these changes, later dismissed

2025-05-07 20:35 UTC, erin-le requested changes
@dhschall: Hello, I noticed a few places where the style could be improved. Could you look over the suggestions?

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/ltage.hh
>                                     bool uncond, void * &bp_history) override;
```suggestion
    void branchPlaceholder(ThreadID tid, Addr pc,
                           bool uncond, void * &bp_history) override;
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/multiperspective_perceptron_tage.cc
> +                              tage->getPathHist(tid, false));
```suggestion
        statisticalCorrector->updateHistories(pc, false, inst, taken,
                                              bi->scBranchInfo, target,
                                              tage->getPathHist(tid, false));
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/statistical_corrector.cc
> +        int8_t conf_ctr, unsigned conf_bits, int hitBank, int altBank)
```suggestion
StatisticalCorrector::calcBias(Addr branch_pc, BranchInfo* bi,
                               bool bias_bit, bool use_conf_ctr,
                               int8_t conf_ctr, unsigned conf_bits,
                               int hitBank, int altBank)
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/statistical_corrector.cc
> +        Addr target, int64_t phist)
```suggestion
StatisticalCorrector::updateHistories(Addr branch_pc, bool speculative,
                                      const StaticInstPtr &inst, bool taken,
                                      BranchInfo * bi, Addr target,
                                      int64_t phist)
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/statistical_corrector.cc
>  {
```suggestion
StatisticalCorrector::scHistoryUpdate(Addr branch_pc,
                                      const StaticInstPtr &inst, bool taken,
                                      Addr target, int64_t phist)
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/tage_sc_l.cc
> +                                    TAGEBase::BranchInfo* bi)
```suggestion
TAGE_SC_L_TAGE::updatePathAndGlobalHistory(ThreadID tid, int brtype,
                                           bool taken, Addr branch_pc,
                                           Addr target,
                                           TAGEBase::BranchInfo* bi)
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/tage_sc_l.cc
> +                                              tage->getPathHist(tid));
```suggestion
                statisticalCorrector->updateHistories(pc, true, inst, taken,
                                                      bi->scBranchInfo, target,
                                                      tage->getPathHist(tid));
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/tage_sc_l.cc
> +                            inst, bi->tageBranchInfo);
```suggestion
    tage->updateHistories(tid, pc, false, taken, target,
                          inst, bi->tageBranchInfo);
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/tage_sc_l.cc
> +                                            tage->getPathHist(tid, false));
```suggestion
        statisticalCorrector->updateHistories(pc, false, inst, taken,
                                              bi->scBranchInfo, target,
                                              tage->getPathHist(tid, false));
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/tage_sc_l.cc
> +{
```suggestion
void
TAGE_SC_L::updateHistories(ThreadID tid, Addr pc, bool uncond, bool taken,
                           Addr target, const StaticInstPtr &inst,
                           void * &bp_history)
{
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/tage_sc_l_64KB.cc
> +        BranchInfo* bi, int & lsum)
```suggestion
int
TAGE_SC_L_64KB_StatisticalCorrector::gPredictions(ThreadID tid, Addr branch_pc,
                                                  BranchInfo* bi, int & lsum)
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/tage_sc_l_64KB.cc
> +{
```suggestion
void
TAGE_SC_L_64KB_StatisticalCorrector::gUpdates(ThreadID tid, Addr pc,
                                              bool taken, BranchInfo* bi)
{
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/tage_sc_l_64KB.hh
> +        int & lsum) override;
```suggestion
    int gPredictions(ThreadID tid, Addr branch_pc, BranchInfo* bi,
                     int & lsum) override;
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/tage_sc_l_8KB.cc
> +                                                       BranchInfo *bi)
```suggestion
TAGE_SC_L_8KB_StatisticalCorrector::scRecordHistState(Addr branch_pc,
                                                      BranchInfo *bi)
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/tage_sc_l_8KB.cc
> +        BranchInfo* bi)
```suggestion
void
TAGE_SC_L_8KB_StatisticalCorrector::gUpdates(ThreadID tid, Addr pc, bool taken,
                                             BranchInfo* bi)
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/multiperspective_perceptron_tage.cc
> +                    bi->scBranchInfo, target, tage->getPathHist(tid, false));
```suggestion
            statisticalCorrector->updateHistories(pc, false, inst, taken,
                                                  bi->scBranchInfo, target, 
                                                  tage->getPathHist(tid,
                                                                    false));
```

2025-05-07 20:35 UTC, erin-le commented on src/cpu/pred/statistical_corrector.hh
> +        int8_t conf_ctr, unsigned conf_bits, int hitBank, int altBank);
```suggestion
    int calcBias(
        Addr branch_pc, BranchInfo* bi,
        bool bias_bit, bool use_conf_ctr,
        int8_t conf_ctr, unsigned conf_bits, int hitBank, int altBank);
```

2025-05-08 07:08 UTC, dhschall commented
@erin-le, thanks for the suggestions. I melted them into the corresponding commits and hope I did not forget something.
I've also fixed a bunch of other styling issues not related to my changes.
Let me know if something is still missing.

2025-05-12 20:26 UTC, erin-le reviewed
@dhschall: Hello, sorry for the delay. Just some more suggestions for spacing to make the style more consistent within each file. Thanks for your patience with the review process!

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/multiperspective_perceptron_tage.cc
> +                0 /* hitBank: unused */, 0 /* altBank: unused*/);
```suggestion
        statisticalCorrector->condBranchUpdate(tid, pc, taken,
                                               bi->scBranchInfo, target,
                                               false /* bias_bit: unused */ ,
                                               0 /* hitBank: unused */,
                                               0 /* altBank: unused*/);
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/multiperspective_perceptron_tage_64KB.cc
> +        StatisticalCorrector::BranchInfo* bi, int & lsum)
```suggestion
        StatisticalCorrector::BranchInfo *bi, int &lsum)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/multiperspective_perceptron_tage_64KB.cc
> +        StatisticalCorrector::BranchInfo* bi)
```suggestion
        StatisticalCorrector::BranchInfo *bi)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/multiperspective_perceptron_tage_8KB.cc
> +        StatisticalCorrector::BranchInfo* bi, int & lsum)
```suggestion
        StatisticalCorrector::BranchInfo *bi, int &lsum)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/multiperspective_perceptron_tage_8KB.cc
> +        StatisticalCorrector::BranchInfo* bi)
```suggestion
        StatisticalCorrector::BranchInfo *bi)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/multiperspective_perceptron_tage_8KB.hh
> +            StatisticalCorrector::BranchInfo* bi, int &lsum) override;
```suggestion
            StatisticalCorrector::BranchInfo *bi, int &lsum) override;
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/multiperspective_perceptron_tage_8KB.hh
> +            StatisticalCorrector::BranchInfo* bi) override;
```suggestion
            StatisticalCorrector::BranchInfo *bi) override;
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/multiperspective_perceptron_tage_64KB.hh
> +            StatisticalCorrector::BranchInfo* bi) override;
```suggestion
            StatisticalCorrector::BranchInfo *bi) override;
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/multiperspective_perceptron_tage_64KB.hh
> +            StatisticalCorrector::BranchInfo* bi, int &lsum) override;
```suggestion
            StatisticalCorrector::BranchInfo *bi, int &lsum) override;
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/statistical_corrector.cc
> +                                      BranchInfo * bi, Addr target,
```suggestion
                                      BranchInfo *bi, Addr target,
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/statistical_corrector.cc
> +StatisticalCorrector::calcBias(Addr branch_pc, BranchInfo* bi, bool bias_bit,
```suggestion
StatisticalCorrector::calcBias(Addr branch_pc, BranchInfo *bi, bool bias_bit,
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/statistical_corrector.cc
> +                                BranchInfo* bi, bool prev_pred_taken,
```suggestion
                                BranchInfo *bi, bool prev_pred_taken,
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/statistical_corrector.cc
> +                              std::vector<int8_t> & w, BranchInfo* bi)
```suggestion
                              std::vector<int> &length,
                              std::vector<int8_t> *tab, int nbr, int logs,
                              std::vector<int8_t> &w, BranchInfo *bi)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/statistical_corrector.cc
> +                               std::vector<int8_t> & w)
```suggestion
                               std::vector<int> &length,
                               std::vector<int8_t> *tab, int nbr, int logs,
                               std::vector<int8_t> &w)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/statistical_corrector.cc
> +                                    std::vector<int8_t> & w, int8_t wInitValue)
```suggestion
                                    std::vector<int8_t> *&table,
                                    unsigned logNumEntries,
                                    std::vector<int8_t> &w, int8_t wInitValue)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/statistical_corrector.hh
> +        BranchInfo * tage_bi, Addr target, int64_t phist);
```suggestion
        BranchInfo *tage_bi, Addr target, int64_t phist);
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/statistical_corrector.hh
> +        ThreadID tid, Addr pc, bool taken, BranchInfo* bi) = 0;
```suggestion
        ThreadID tid, Addr pc, bool taken, BranchInfo *bi) = 0;
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l.cc
> +TAGE_SC_L_TAGE::branchTypeExtra(const StaticInstPtr & inst)
```suggestion
TAGE_SC_L_TAGE::branchTypeExtra(const StaticInstPtr& inst)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l.cc
> +                bi->tageBranchInfo->altBank);
```suggestion
            statisticalCorrector->condBranchUpdate(tid, pc, taken,
                                                   bi->scBranchInfo, target,
                                                   bias,
                                                   bi->tageBranchInfo->hitBank,
                                                   bi->tageBranchInfo->
                                                   altBank);
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l.cc
> +                bi->tageBranchInfo->altBank);
```suggestion
        pred_taken = statisticalCorrector->scPredict(tid, pc, cond_branch,
                                                     bi->scBranchInfo,
                                                     pred_taken, bias,
                                                     use_tage_ctr, tage_ctr,
                                                     tage->getTageCtrBits(),
                                                     bi->tageBranchInfo->
                                                     hitBank,
                                                     bi->tageBranchInfo->
                                                     altBank);
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_64KB.cc
> +                                                  BranchInfo* bi, int & lsum)
```suggestion
                                                  BranchInfo *bi, int &lsum)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_64KB.cc
> +                                                    BranchInfo* bi,
```suggestion
                                                    BranchInfo *bi,
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_64KB.cc
> +                                              bool taken, BranchInfo* bi)
```suggestion
                                              bool taken, BranchInfo *bi)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_64KB.cc
> +                                          TAGEBase::BranchInfo* bi, int nrand)
```suggestion
                                          TAGEBase::BranchInfo *bi, int nrand)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_64KB.cc
> +                                      TAGEBase::BranchInfo* bi)
```suggestion
                                      TAGEBase::BranchInfo *bi)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_64KB.hh
> +                     int & lsum) override;
```suggestion
                     int &lsum) override;
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_8KB.cc
> +                                             BranchInfo* bi)
```suggestion
                                             BranchInfo *bi)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_8KB.cc
> +                                         TAGEBase::BranchInfo* bi, int nrand)
```suggestion
                                         TAGEBase::BranchInfo *bi, int nrand)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_8KB.hh
> +    unsigned getIndBiasBank(Addr branch_pc, BranchInfo* bi, int hitBank,
```suggestion
    unsigned getIndBiasBank(Addr branch_pc, BranchInfo *bi, int hitBank,
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_8KB.hh
> +    void gUpdates(ThreadID tid, Addr pc, bool taken, BranchInfo* bi) override;
```suggestion
    void gUpdates(ThreadID tid, Addr pc, bool taken, BranchInfo *bi) override;
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l.hh
> +    int branchTypeExtra(const StaticInstPtr & inst) override;
```suggestion
    int branchTypeExtra(const StaticInstPtr& inst) override;
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_64KB.hh
> +    void gUpdates(ThreadID tid, Addr pc, bool taken, BranchInfo* bi) override;
```suggestion
    void gUpdates(ThreadID tid, Addr pc, bool taken, BranchInfo *bi) override;
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_8KB.cc
> +    ThreadID tid, Addr branch_pc, BranchInfo* bi, int & lsum)
```suggestion
    ThreadID tid, Addr branch_pc, BranchInfo* bi, int& lsum)
```

2025-05-12 20:26 UTC, erin-le commented on src/cpu/pred/tage_sc_l_8KB.hh
> +                     int & lsum) override;
```suggestion
    int gPredictions(ThreadID tid, Addr branch_pc, BranchInfo *bi,
                     int &lsum) override;
```

2025-05-13 06:31 UTC, dhschall commented
Hi @erin-le, thanks for the hints. I've included your suggestions and found several other places where things are inconsistent.
The only not-so-nice thing is that now it's a mess of the new feature and refactoring. It probably would have been better to have a separate PR/commit for code refactoring.
Anyway, it's already done and the refactoring is needed.
Therefore, ff you find something else, let me know, it's no problem to fix it.

2025-05-13 21:14 UTC, erin-le approved these changes
Thanks for the changes! This LGTM

2025-05-14 21:54 UTC, merged