test: Update asmtest script
gem5/gem5 pull request #206
Opened 2023-08-21 02:18 UTC by rogerchang23424

Upload the config script to make it only for riscv asmtest and replace Resource with obtain_resourse

Change-Id: I0bab96ea352b7ce1c6838203bfa13eee795f41f9

2023-08-21 15:07 UTC, powerjg commented
Looks great to me... Thanks for the contribution! I'll let Bobby sign off.

2023-08-21 20:25 UTC, BobbyRBruce requested changes

2023-08-21 20:25 UTC, BobbyRBruce commented on tests/gem5/asmtest/configs/riscv_asmtest.py
> +binary = obtain_resource(args.resource)
So, I'd quite like there to continue to be an `resource_directory=args.resource_directory` option here. When testing I store resources downloaded in "tests/gem5/resources".

2023-08-21 20:25 UTC, BobbyRBruce commented on tests/gem5/asmtest/tests.py
> -
I'd like this code-readded, unless there's a good argument to remove it.

2023-08-22 20:59 UTC, BobbyRBruce approved these changes

2023-08-22 20:59 UTC, merged