mem: fix bug in 3-level cache
gem5/gem5 pull request #265
Opened 2023-09-04 09:20 UTC by y553546436

The L3 cache did not work due to argument type mismatch in the call to the constructor `DMAController`. The second argument is expecting a `RubySystem` type but the code passes in a `cache_line_size` variable.
After I change the second argument to `self.ruby_system` everything works.

2023-09-05 19:30 UTC, BobbyRBruce commented
@y553546436: Could you provide a way to reproduce the bug this patch fixes?

2023-09-13 05:12 UTC, hnpl commented
@BobbyRBruce you test by reusing `configs/example/gem5_library/x86-ubuntu-run-with-kvm.py` with the following change,

```
diff --git a/configs/example/gem5_library/x86-ubuntu-run-with-kvm.py b/configs/example/gem5_library/x86-ubuntu-run-with-kvm.py
index f55ec60f21..a6c30ac04e 100644
--- a/configs/example/gem5_library/x86-ubuntu-run-with-kvm.py
+++ b/configs/example/gem5_library/x86-ubuntu-run-with-kvm.py
@@ -53,27 +53,21 @@ from gem5.simulate.simulator import Simulator
 from gem5.simulate.exit_event import ExitEvent
 from gem5.resources.workload import Workload
 
# This runs a check to ensure the gem5 binary is compiled to X86 and to the
# MESI Two Level coherence protocol.
requires(
    isa_required=ISA.X86,
-    coherence_protocol_required=CoherenceProtocol.MESI_TWO_LEVEL,
+    coherence_protocol_required=CoherenceProtocol.MESI_THREE_LEVEL,
    kvm_required=True,
)

-from gem5.components.cachehierarchies.ruby.mesi_two_level_cache_hierarchy import (
-    MESITwoLevelCacheHierarchy,
+from gem5.components.cachehierarchies.ruby.mesi_three_level_cache_hierarchy import (
+    MESIThreeLevelCacheHierarchy,
 )
 
 # Here we setup a MESI Two Level Cache Hierarchy.
-cache_hierarchy = MESITwoLevelCacheHierarchy(
+cache_hierarchy = MESIThreeLevelCacheHierarchy(
     l1d_size="16kB",
     l1d_assoc=8,
     l1i_size="16kB",
     l1i_assoc=8,
     l2_size="256kB",
     l2_assoc=16,
-    num_l2_banks=1,
+    l3_size="1MiB",
+    l3_assoc=32,
+    num_l3_banks=8
 )
```

2023-09-13 05:16 UTC, hnpl requested changes
This change looks good to me. I suggest to remove the commented out lines.

2023-09-13 05:16 UTC, hnpl commented on src/python/gem5/components/cachehierarchies/ruby/mesi_three_level_cache_hierarchy.py
> +                # ctrl.dma_sequencer = DMASequencer(version=i, in_ports=port)
```suggestion

```

2023-09-13 05:16 UTC, hnpl commented on src/python/gem5/components/cachehierarchies/ruby/mesi_three_level_cache_hierarchy.py
> +                # ctrl.ruby_system = self.ruby_system
```suggestion

```

2023-09-18 19:00 UTC, y553546436 commented
@hnpl Thanks for helping find a test. @BobbyRBruce Is there anything more I can do to help integrate this fix?

2023-09-20 19:17 UTC, BobbyRBruce commented
> @hnpl Thanks for helping find a test. @BobbyRBruce Is there anything more I can do to help integrate this fix?

I've changed this patch slightly to fix it. The tests are running now. When they patch I'll merge this. Thanks!

2023-09-29 17:51 UTC, BobbyRBruce approved these changes

2023-09-29 17:57 UTC, Harshil2107 approved these changes

2023-09-29 17:59 UTC, merged