mem-cache: Fix bug in classic cache while clflush
gem5/gem5 pull request #274
Opened 2023-09-06 03:14 UTC by hnpl

This change, https://github.com/gem5/gem5/pull/205, mistakenly allocates write buffer for clflush instruction when there's a cache miss. However, clflush in gem5 is not a write instruction. Thus, the cache should allocate miss buffer in this case.

Change-Id: I9c1c9b841159c4420567e9c929e71e4aa27d5c28

2023-09-06 03:16 UTC, hnpl commented
Tested with setting a page uncacheable in full system mode.

The change in #205 results in an assertion error when calling allocatesWriteBuffer.

#205 + #274 works.

2023-09-06 03:19 UTC, BobbyRBruce submitted a review, later dismissed

2023-09-06 16:28 UTC, powerjg commented
Before we merge... How do we know this doesn't break arm cache management instructions?

2023-09-06 16:29 UTC, powerjg requested changes
Blocking until we are sure this doesn't affect Arm instructions

2023-09-06 16:55 UTC, giactra commented
Being summoned by the Arm mention =P

Unless I am missing something, it seems to me this commit is sort of reverting https://github.com/gem5/gem5/pull/205
Before #205, the code was:

        if (pkt->isWrite()) {
            allocateWriteBuffer(pkt, forward_time);
        } else {
            allocateMissBuffer(pkt, forward_time);
        }

With this patch we go back to:

        if (pkt->isWrite()) {
            allocateWriteBuffer(pkt, forward_time);
        } else if (pkt->isRead()) {
            allocateMissBuffer(pkt, forward_time);
        } else {
            assert(pkt->isCleanInvalidateRequest());
            allocateMissBuffer(pkt, forward_time);
        }

Which is essentially the same other than the extra assert. IMHO this extra clause is not really worth it. Shall we just revert #205 ?

2023-09-07 00:15 UTC, hnpl commented
I agree that the if/else statements here are rather silly.

However, the problem before #205 was that, in the else statement, the code asserts that the packet is a read. Essentially, within an uncacheable region, classic cache only serves either read or write requests.

```
        if (pkt->isWrite()) {
            allocateWriteBuffer(pkt, forward_time);
        } else {
            assert(pkt->isRead());
            allocateMissBuffer(pkt, forward_time);
        }
```

#205 and #274 basically loosen this restriction to serving read/write/clflush on uncacheable regions.

The comments in #205 show that clflush can happen on uncacheable regions.

2023-09-07 07:48 UTC, giactra requested changes
Yeah apologies I missed that assert.
In that case I believe the code should actually be:

        if (pkt->isWrite()) {
            allocateWriteBuffer(pkt, forward_time);
        } else {
            assert(pkt->isRead() || pkt->isCleanInvalidateRequest());
            allocateMissBuffer(pkt, forward_time);
        }

2023-09-08 18:17 UTC, hnpl commented
I reworded the code comments and change the assert as suggested.

2023-09-11 18:58 UTC, giactra approved these changes
Thanks for the changes!

2023-09-12 15:34 UTC, BobbyRBruce approved these changes

2023-09-12 17:49 UTC, powerjg approved these changes

2023-09-14 08:14 UTC, merged