sim-se: zero out memory allocated via brk()
gem5/gem5 pull request #343
Opened 2023-09-21 02:04 UTC by nmosier

The syscall emulation of brk() incorrectly did not ensure that newly allocated memory was zero-initialized, which Linux guarantees and which seems to be the expectation of glibc's malloc() and free() implementation. This patch fixes the incorrect behavior by zero- initalizing all memory allocations via brk().

GitHub issue: https://github.com/gem5/gem5/issues/342

Change-Id: I53cf29d6f3f83285c8e813e18c06c2e9a69d7cc2

2023-09-21 11:38 UTC, giactra requested changes
That's interesting. I looked at the brk(2) man pages [1][2] and it does not reference any sort of zeroing happening when the program break gets increased. I know this is automatically done when the allocator ask the OS memory with mmap+/dev/zero but I don't see any zeroing being referenced by the linux kernel with the program break.

Could you point me to some documentation describing this behaviour?

[1]: https://man7.org/linux/man-pages/man2/brk.2.html
[2]: https://linux.die.net/man/2/brk

2023-09-21 11:38 UTC, giactra commented on src/sim/syscall_emul.cc
> +    if (new_brk > brk_point) {
Nit: Could you add a comment here just describing the zeroing?

2023-09-21 16:31 UTC, nmosier commented
I look into the issue a bit further, and it looks like the real bug is due to the fact that the `gem5::MemState::updateBrkRegion()` method does not unmap deallocated heap pages when the program break recedes. While I can't point to documentation yet showing that pages newly allocated with brk() should be zero-filled, I was able to find exactly where in glibc malloc's source that they encode this assumption: [malloc/malloc.c, line 517](https://sourceware.org/git?p=glibc.git;a=blob;f=malloc/malloc.c;h=d0bbbf371048ee8aa8a30c03b189cb268b8ad9e4;hb=refs/heads/master#l517):
```c
/*  MORECORE_CLEARS           (default 1)                                                                                                                                                                                                     
     The degree to which the routine mapped to MORECORE zeroes out                                                                                                                                                                            
     memory: never (0), only for newly allocated space (1) or always                                                                                                                                                                          
     (2).  The distinction between (1) and (2) is necessary because on                                                                                                                                                                        
     some systems, if the application first decrements and then                                                                                                                                                                               
     increments the break value, the contents of the reallocated space                                                                                                                                                                        
     are unspecified.                                                                                                                                                                                                                         
 */
```
and in [sysdeps/unix/sysv/linux/Makefile](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/Makefile;h=063719bae645b24a4474729640453fa4b5a63056;hb=refs/heads/master) they set the default for Linux to be 2, i.e., memory returned by MORECORE (which defaults to sbrk()) is always zero-filled.

What I had before, zero-filling newly allocated brk() memory directly, would also work, but the Linux kernel doesn't appear to do that. It seems to only unmap freed pages when the program break recedes.

2023-09-22 02:42 UTC, nmosier commented
I'm wondering if the test that failed is flaky, since all tests passed locally on my machine.

2023-09-22 15:01 UTC, powerjg commented
Yeah, we're having intermittent network issues with some of our runners where the test binaries are failing to download. Hopefully it will work when we re-run it.

2023-09-25 14:06 UTC, giactra commented
> I look into the issue a bit further, and it looks like the real bug is due to the fact that the `gem5::MemState::updateBrkRegion()` method does not unmap deallocated heap pages when the program break recedes. While I can't point to documentation yet showing that pages newly allocated with brk() should be zero-filled, I was able to find exactly where in glibc malloc's source that they encode this assumption: [malloc/malloc.c, line 517](https://sourceware.org/git?p=glibc.git;a=blob;f=malloc/malloc.c;h=d0bbbf371048ee8aa8a30c03b189cb268b8ad9e4;hb=refs/heads/master#l517):
> 
> ```c
> /*  MORECORE_CLEARS           (default 1)                                                                                                                                                                                                     
>      The degree to which the routine mapped to MORECORE zeroes out                                                                                                                                                                            
>      memory: never (0), only for newly allocated space (1) or always                                                                                                                                                                          
>      (2).  The distinction between (1) and (2) is necessary because on                                                                                                                                                                        
>      some systems, if the application first decrements and then                                                                                                                                                                               
>      increments the break value, the contents of the reallocated space                                                                                                                                                                        
>      are unspecified.                                                                                                                                                                                                                         
>  */
> ```
> 
> and in [sysdeps/unix/sysv/linux/Makefile](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/Makefile;h=063719bae645b24a4474729640453fa4b5a63056;hb=refs/heads/master) they set the default for Linux to be 2, i.e., memory returned by MORECORE (which defaults to sbrk()) is always zero-filled:
> 
> ```
> ifeq ($(subdir),malloc)
> CFLAGS-malloc.c += -DMORECORE_CLEARS=2
> endif
> ```
> 
> What I had before, zero-filling newly allocated brk() memory directly, would also work, but the Linux kernel doesn't appear to do that. It seems to only unmap freed pages when the program break recedes.

Thanks @nmosier for taking the time to look into the documentation. Pointing to the glibc implementation really helps on clearing out some doubts!

2023-09-25 14:19 UTC, giactra requested changes
Code looks great I just have a minor comment

2023-09-25 14:19 UTC, giactra commented on src/sim/mem_state.cc
> +     * glibc malloc.
Nit: I would reword this part of the comment as IMHO it's not entirely accurate to label previous behaviour as intrinsically buggy.

From what I understood not zeroing out the old heap is technically legal and it does not violate any glibc assumption as long as glibc is informed by such behaviour via the MORECORE_CLEAR value. We should just note that Linux expect the zeroing and unmapping pages anyway regardless of the MORECORE_CLEAR is the safest option that works for every system.

2023-10-06 21:22 UTC, powerjg approved these changes
lgtm! Thanks for the fix

2023-10-09 12:48 UTC, giactra approved these changes

2023-10-09 12:48 UTC, merged