util: Update the GitHub Self-Hosted Runners
gem5/gem5 pull request #371
Opened 2023-09-29 12:11 UTC by BobbyRBruce

1. All VMs are deployable from a single Vagrantfile (per host machine).
2. Runners within VMs are now ephemeral. They cease to exist after a job is complete. After the VM cleans the workspace and creates a new runner. This will reduce old data, scripts, and images causing space issues on our VMs
3. No more 'vm_manager.sh' script. The standard `vagrant` command to manage the VMs will work.
4. Adds Copyright notices where missing.

2023-09-29 12:13 UTC, BobbyRBruce commented
I've created the following VMs using the changes in this PR:

* loupe-test-for-bobby-builder-1
* loupe-test-for-bobby-builder-2
* loupe-test-for-bobby-runner-1
* loupe-test-for-bobby-runner-2

I think they work but, unfortunately, the best test for  us is to just use them and see how they perform. It shouldn't take too long to see any obvious problems.

2023-09-29 19:35 UTC, mkjost0 submitted a review, later dismissed

2023-10-03 16:53 UTC, BobbyRBruce commented
These runners appear to be causing our compiler tests to fail.


https://github.com/gem5/gem5/actions/runs/6348223508/job/17244466433 fails with:

```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/vagrant/_work/_actions/actions/checkout/v3'. Did you forget to run actions/checkout before running your local action?
```

This one appears to just have timed out: https://github.com/gem5/gem5/actions/runs/6348223508/job/17244463049


This one, https://github.com/gem5/gem5/actions/runs/6348223508/job/17244466433, fails with:

```
Error: An error occurred trying to start process '/usr/bin/tar' with working directory '/home/vagrant/_work/_actions/_temp_93e030a2-ec91-4b7a-8ac9-9e416478beb3/_staging'. No such file or directory
```

All the other failures in https://github.com/gem5/gem5/actions/runs/6348223508 appear to have one of these three issues.

While I can't explain the timeout, the other two look like these runners are cleaning up the "_work" directory too early somehow. The job isn't complete but fils are already being removed and causing problems.

2023-10-06 21:37 UTC, powerjg commented on util/github-runners-vagrant/Vagrantfile
> +HOSTNAME="<VM NAME>"
I think this works: `ENV['VM_NAME']` and `ENV['TOKEN']`

2023-10-06 21:38 UTC, powerjg approved these changes

2023-10-06 21:39 UTC, powerjg requested changes
Remove the commit that shouldn't be here

2023-10-06 22:54 UTC, BobbyRBruce commented
> Remove the commit that shouldn't be here

It has been wiped.

2023-10-06 23:26 UTC, powerjg approved these changes

2023-10-09 04:52 UTC, merged