tests: updated the nightly tests to use SST 13.0.0
gem5/gem5 pull request #441
Opened 2023-10-12 01:28 UTC by kaustav-goswami

PR https://github.com/gem5/gem5/pull/396 updates the gem5 SST bridge to use StandardMem in SST. This change updates the nightly tests to use SST 13.0.0 instead of SST 11.1.0. It also updates the dockerfile.

Change-Id: I5c109c40379d2f09601a1c9f19c51dd716c6582e

2023-10-12 14:21 UTC, BobbyRBruce requested changes
The nightly.sh script is deprecated. You need to update ".github/workflows/daily-tests.yaml".

2023-10-13 01:21 UTC, BobbyRBruce commented
I've updated the docker image.

2023-10-13 21:25 UTC, powerjg approved these changes

2023-10-13 21:26 UTC, BobbyRBruce approved these changes

2023-10-13 21:31 UTC, merged