cpu: Implement taken-only history
gem5/gem5 pull request #499
Opened 2023-10-23 21:10 UTC by dhschall

Note: This PR is WIP and still depends on #455. Will be rebased if refactoring is merged. This PR concerns only about the second commit.

Modern server CPUs implement a 'taken-only' global history
(https://ieeexplore.ieee.org/document/9246215).
In it the history is formed out of two bit hashes (branch PC and
target) from all taken branches. Taken history makes speculative
history management much easier. Since at the time a prediction
must be made (at fetch) there is no information whether at the current
PC address is a branch or not. That is only known after decode or
from a BTB hit. To save BTB entries 'never taken' branches are not
installed in the BTB. For an undetected branch the speculative history
must either be fixed after decode or becomes incorrect.
Taken-only history naturally overcomes this problem.

2023-11-13 19:48 UTC, Harshil2107 commented
Hello @andysan ,
Would it be alright if I assign this PR to you? Please be aware that being assigned to a PR implies that you are responsible for ensuring that the PR is reviewed and merged.

2024-01-05 18:09 UTC, ivanaamit commented
Just checking in -- what is the status of this PR? Thanks.

2024-03-01 19:07 UTC, rjc-arch requested changes
Hi @dhschall - this all looks good to me. I'm not very familiar with the details of the branch predictor implementations, but I can't see any obvious problems.

I have commented on some small, mostly cosmetic changes you might consider. There are also a number of places with incorrect/inconsistent indentation/formatting that I haven't commented on, but which you might also like to review (mostly in the `tage_base.(hh|cc)` files).

Unless we can find someone with a deeper knowledge of the branch predictors to do a review, I think this looks good.

2024-03-01 19:07 UTC, rjc-arch commented on src/cpu/pred/bpred_unit.hh
> +     * requires a BTB hit. This function will generage a placeholder for
Typo: 'generage' -> 'generate'.

2024-03-01 19:07 UTC, rjc-arch commented on src/cpu/pred/bpred_unit.cc
> +    panic("Not implemented for this BP!\n");
Optional: you could add a bit more context to the message here to avoid the user  having to look in the source code for the reason. For example "branchPlaceholder() not implemented for this BP." .

2024-03-01 19:07 UTC, rjc-arch commented on src/cpu/pred/bpred_unit.hh
> +     * only create the branch history object but not update BPU internal.
Typo(?): "BPU internal" -> "the BPU internal state"?

2024-03-01 19:07 UTC, rjc-arch commented on src/cpu/pred/bpred_unit.hh
> +     * If the branch turns to be wrong then decode or commit will
Typo 'user' -> 'use'.
"If the branch turns out to be wrong then decode or commit will
be able to use the normal squash functionality..."

2024-03-01 19:07 UTC, rjc-arch commented on src/cpu/pred/bpred_unit.hh
> +     * @param PC The branch's PC.
Nit: 'PC' -> 'pc'.

2024-03-01 19:07 UTC, rjc-arch commented on src/cpu/pred/bpred_unit.hh
> +     * @param uncond Wheather or not this branch is an unconditional branch.
Typo: 'wheather' -> 'whether'.

2024-03-01 19:07 UTC, rjc-arch commented on src/cpu/pred/bpred_unit.hh
> +     * Squashes a particular branch instance. Reverts
Optional suggestion: since this patch changes where the history items are deleted, you could add a comment here to explain which method is responsible for deleting the history items. 
Although it's not part of your code changes, I've found the memory management of the BP history, etc, quite complex. Some documentation might not go amiss.

2024-03-01 19:07 UTC, rjc-arch commented on src/cpu/pred/tage_base.cc
> +            tHist.globalHistory[histBufferSize - maxHist + i]
Nit: For clarity I would put braces around the for loop body since it is split over two lines.

2024-03-01 19:07 UTC, rjc-arch commented on src/cpu/pred/tage_base.cc
>           // through pt[0 .. maxHist - 1].
`pt` has been removed now.

2024-03-01 19:07 UTC, rjc-arch commented on src/cpu/pred/tage_base.hh
> +     * @param pc The unshifted branch PC.
`pc` has been re-named to `branch_pc`.

2024-03-01 19:10 UTC, rjc-arch commented
We have also run some performance regressions of this PR using SPEC 2017 SimPoints, and have confirmed that it does not cause any unexpected changes in simulated performance.

2024-07-08 15:42 UTC, dhschall commented on src/cpu/pred/bpred_unit.hh
> +     * Squashes a particular branch instance. Reverts
I've added more details on the PredictorHistory object which hopefully helps to better understand its live-cycle

2024-12-12 20:09 UTC, erin-le commented
@dhschall Hello, thank you for your contribution! The gem5 dev team would like to help you get this PR in, but we have a few questions about this and your other PRs. 

First, could you clarify how this PR, https://github.com/gem5/gem5/pull/359, https://github.com/gem5/gem5/pull/1854, https://github.com/gem5/gem5/pull/1855 fit together? 

Also, how should these PRs be tested, i.e. should they all be cherry-picked onto one branch and tested together, tested completely separately, or something in between?  Furthermore, how have you been testing these PRs?

Once the gem5 dev team has a better understanding of these PRs and how they should be tested, we can help to develop a plan for testing these changes and getting them into gem5. Thank you!

2024-12-12 21:30 UTC, dhschall commented
Thank you @erin-le for the quick feedback!
This PR is the basis for all the other PR's mentioned. It is mostly refactoring of the branch predictor to make the other changes possible/easier. Furthermore, it enables adding _surprise-branches_, branches that were not detected by the front-end due to BTB misses. This will become relevant for the decoupled front-end later.
As for now, this PR should not change the behavior. @rjc-arch already did some regression tests with SPEC workloads a while ago, and the behavior didn't change then.

#1854 Adds support for speculatively updating TAGE-SC-L (see #1341 for the discussion). It is independent of the other changes.
#1855 Adds support for taken-only history which is needed for the decoupled front-end.
#359 Is the implementation of the decoupled front-end. However, it is not mergeable as the cache interface changes. Also, I did some significant refactoring, but I need a bit more time to finalize and test it. #359 depends on this PR and #1855.

For testing, I am using a few more complex server workloads in full system simulations (see [graph](https://github.com/user-attachments/assets/892542d2-8ca0-4e3a-a871-29b920aa292c) in #1854). One workload is a NodeJS web server running inside a docker container that is invoked by a client running on a second node. Two other workloads (libs and compression) are taken from Google's fleet-bench benchmark suite.
I'll run again the tests for this PR and add the graph. If you have some testing infrastructure or some workloads, you want me to run, let me know. I've also asked @rjc-arch to run SPEC simpoints again, but he is quite busy atm. so he might not be able to help me with further testing.

2024-12-13 16:33 UTC, powerjg commented
Thanks for all of the details, David! I think it would be good for us here at UCD to run some SPEC simpoints and publish the data. We'll get on that.

It sounds like this PR is ready to go, is that right?

2024-12-13 17:01 UTC, dhschall commented
Thanks, @powerjg! Do you mean publishing the simpoints as executables, runnable on gem5, or that you publish the performance numbers? The former would be awesome to establish a common baseline for testing and validation. 
I don't know how the testing works but if you could integrate it with the CI to run these tests from time to time to observe how the simulated performance changes over time that would also be great but I know it takes time...

FE PR, from my side, yes. I've fixed some minor indentation issues and pre-commit checks.

2024-12-13 17:07 UTC, powerjg commented
I mean to publish the results from SPEC simpoints. Annoyingly, the SPEC license doesn't allow us to distribute the simpoints.

We could potentially integrate this into the testing infrastructure, since we control it. The main reason we haven't is the amount of time/resources that the simulation takes. Maybe we can integrate it into the weekly tests, though. We'll give it some thought!

2025-03-06 15:40 UTC, rjc-arch approved these changes
Hi @dhschall, 

Thank you for for the updates! This PR looks good to me. 

I have made a few comments on some very small issues like code formatting which you could fix, but I'd be happy for this PR to be merged.

We have also re-run the performance regressions mentioned above, and have re-confirmed that it does not cause any unexpected changes in simulated performance.

2025-03-06 15:40 UTC, rjc-arch commented on src/cpu/pred/2bit_local.cc
> +                   Addr target, const StaticInstPtr &inst, void * &bp_history)
Nit: Code formatting: the alignment is slightly off on some of these function definitions. (The same applies to some other files too.)

2025-03-06 15:40 UTC, rjc-arch commented on src/cpu/pred/bpred_unit.hh
> +     * @param pc The branch's PC.
Nit: The `tid` Thread ID parameter should also be listed here.

2025-03-06 15:40 UTC, rjc-arch commented on src/cpu/pred/bpred_unit.hh
> +     * Squashes a particular branch instance. Reverts
Thanks for the extra comments - these are very helpful!

2025-03-06 15:40 UTC, rjc-arch commented on src/cpu/pred/tage_base.hh
> +            comp = ( tmp << (compLength-1)) | (comp >> 1);
Nit: there's an extra space after the opening brace.

2025-03-06 15:40 UTC, rjc-arch commented on src/cpu/pred/tage_base.hh
> +     * @param bi Pointer to the branch associated with the state
Nit: missing the `tid` parameter.

2025-03-06 15:40 UTC, rjc-arch commented on src/cpu/pred/tage_base.hh
> +     * @param bi Pointer to the branch associated with the state
Nit: missing the `tid` parameter.

2025-03-06 15:40 UTC, rjc-arch commented on src/cpu/pred/tage_base.hh
> +     */
Nit: missing the `bi` parameter.

2025-03-06 15:40 UTC, rjc-arch commented on src/cpu/pred/tage_base.cc
> +        tHist.gHist[0] = (bv & 1) ? 1 : 0;
The syntax `*(tHist.gHist) = (bv & 1) ? 1 : 0;` might be slightly clearer here, to avoid making `tHist.gHist` look like an array. That's just a subjective opinion though, so feel free to ignore this comment if you don't agree.

2025-03-06 18:00 UTC, dhschall commented
Thanks @rjc-arch! I've addressed all your formating suggestions. @andysan can you maybe have a second if its all right to get it merged?

2025-03-07 10:04 UTC, andysan approved these changes

2025-03-11 09:54 UTC, merged