resources,stdlib: update suites to lazy download
gem5/gem5 pull request #609
Opened 2023-11-27 22:32 UTC by Harshil2107

- suites will lazily download all the resources when the __iter__ method is called instead of download all of them upon initialization.

Change-Id: I46a2fe00712818cda6282a71c1470f596cb1f06c

2023-11-27 22:41 UTC, powerjg commented
Put this on the list for 23.1!

2023-11-28 01:26 UTC, powerjg commented on src/python/gem5/resources/resource.py
> +    def get_constituent_workloads(self) -> List[Tuple[str, str]]:
How about `get_workload_ids`

2023-11-28 01:26 UTC, powerjg commented on src/python/gem5/resources/resource.py
> +        workloads_id_map: Dict[Tuple[str, str], Set[str]] = {},
**MUST** update the documentation below. This new parameter is not obvious at all. Please update for all new parameters :)

2023-11-29 16:47 UTC, powerjg requested changes

2023-11-29 16:47 UTC, powerjg commented on src/python/gem5/resources/resource.py
> +        gem5_version: Optional[str] = core.gem5Version,
These new parameters are also not included in the documentation. Please update.

2023-11-29 21:23 UTC, powerjg approved these changes

2023-11-29 21:53 UTC, BobbyRBruce requested changes
I don't see the point in this. With this change we're downloading all the workloads in a suite the first time we ever iterate through it. Why? This is no better than downloading all the workloads on construction and adds   lot of confusing logic to get there.

2023-11-29 22:04 UTC, Harshil2107 commented
The main reason is that we download all the workloads for a suite that we might not need and this takes a lot of time. For example the micro benchmarks suite has 40+ workloads with different binaries. With this change we can filter the suite with input groups and get information about the workloads in the suite without downloading the resources. We will only download when we call the `__iter__` that is when they actually want to use the suite.

An example of this would be that in our configs/example/gem5_library/riscvmatched-microbenchmark-suite.py example the line:
`board.set_workload(list(microbenchmarks.with_input_group("cca"))[0])`

will download all the resources for all the workloads when we only want one workload with the "cca" input group. With this change on the filtered workloads will be downloaded that is just one workload with the input group "cca"

2023-11-29 22:09 UTC, BobbyRBruce commented
> The main reason is that we download all the workloads for a suite that we might not need and this takes a lot of time. For example the micro benchmarks suite has 40+ workloads with different binaries. With this change we can filter the suite with input groups and get information about the workloads in the suite without downloading the resources. We will only download when we call the `__iter__` that is when they actually want to use the suite.
> 
> An example of this would be that in our configs/example/gem5_library/riscvmatched-microbenchmark-suite.py example the line: `board.set_workload(list(microbenchmarks.with_input_group("cca"))[0])`
> 
> will download all the resources for all the workloads when we only want one workload with the "cca" input group. With this change on the filtered workloads will be downloaded that is just one workload with the input group "cca"

Is there not a way to just download the data upon construction but only download the actual resource (Disk Images, etc.) when we actually need to load it into the simulation?

2023-11-29 22:14 UTC, Harshil2107 commented
> > The main reason is that we download all the workloads for a suite that we might not need and this takes a lot of time. For example the micro benchmarks suite has 40+ workloads with different binaries. With this change we can filter the suite with input groups and get information about the workloads in the suite without downloading the resources. We will only download when we call the `__iter__` that is when they actually want to use the suite.
> > An example of this would be that in our configs/example/gem5_library/riscvmatched-microbenchmark-suite.py example the line: `board.set_workload(list(microbenchmarks.with_input_group("cca"))[0])`
> > will download all the resources for all the workloads when we only want one workload with the "cca" input group. With this change on the filtered workloads will be downloaded that is just one workload with the input group "cca"
> 
> Is there not a way to just download the data upon construction but only download the actual resource (Disk Images, etc.) when we actually need to load it into the simulation?

This would be a much bigger  change for all the resources, I assume you mean that we only download the resource when a first call to it is actually made?

2023-11-29 22:35 UTC, powerjg commented
> Is there not a way to just download the data upon construction but only download the actual resource (Disk Images, etc.) when we actually need to load it into the simulation?

This is exactly the feedback that I had 😆

2023-11-30 02:13 UTC, BobbyRBruce commented
I've created an alternative approach here: https://github.com/gem5/gem5/pull/625. Let me know what you think and if it meets the requirements.

2023-12-02 01:04 UTC, BobbyRBruce commented
Superseded by #625

2023-12-02 01:04 UTC, closed without merging