tests: switch lulesh to use vega_x86
gem5/gem5 pull request #620
Opened 2023-11-29 15:42 UTC by Harshil2107

Change-Id: Ifbf0fdfd7d8c2bbaad0b6094090acecd1cb8055c

2023-11-29 21:55 UTC, BobbyRBruce requested changes
Can the HACC tests use VEGA? In which case we could just update the `build-gem5` job?

2023-11-29 22:24 UTC, abmerop commented
> Can the HACC tests use VEGA? In which case we could just update the `build-gem5` job?

Anything working in GCN3 works in Vega the last time I tested, so I don't see why not

2023-11-30 02:54 UTC, BobbyRBruce approved these changes

2023-11-30 02:55 UTC, merged

2023-11-30 23:04 UTC, mattsinc commented
> > Can the HACC tests use VEGA? In which case we could just update the `build-gem5` job?
> 
> Anything working in GCN3 works in Vega the last time I tested, so I don't see why not

Sorry I am just seeing this after the ASPLOS deadline.  Looks good and yes in theory we should be able to move fully to VEGA.