misc, stdlib: Update documentation to adhere to RST formatting.
gem5/gem5 pull request #631
Opened 2023-11-30 19:15 UTC by ivanaamit

This PR updates files in `src/python` to adhere to reStructuredText formatting.

2023-11-30 22:13 UTC, Harshil2107 requested changes
The documentation changes look mostly good to me. There are some spelling errors that we might as well fix as we are updating documentation.

2023-11-30 22:13 UTC, Harshil2107 commented on src/python/gem5/resources/resource.py
> +                                  the correct md5 value, the resoruce will be
```suggestion
                                  the correct md5 value, the resource will be
```

This is not related to the reformatting, but resource is misspelled as resoruce. I think we can change change this in this PR as it updates the documentation.

2023-11-30 22:13 UTC, Harshil2107 commented on src/python/gem5/resources/resource.py
>      This function was created to maintain backwards compability for v21.1.0
```suggestion
    This function was created to maintain backwards compatibility for v21.1.0
```
This is not related to the reformat but compatibility is misspelled as compability.

2023-11-30 22:13 UTC, Harshil2107 commented on src/python/gem5/resources/resource.py
> +    has been dropped. Instead users are advized to use the ``obtain_resource``
```suggestion
    has been dropped. Instead users are advised to use the ``obtain_resource``
```
This is not related to the reformat but advised is misspelled as advized.

2023-12-01 00:13 UTC, ivanaamit commented
Good catch, @Harshil2107! I fixed the errors.

2023-12-01 18:31 UTC, Harshil2107 approved these changes
lgtm

2023-12-01 19:43 UTC, merged