mem-ruby: allow comparison of int and Addr in SLICC
gem5/gem5 pull request #701
Opened 2023-12-20 09:26 UTC by arteen1000

allow easy isolation of specific addresses in coherence protocols. useful for debugging.

Change-Id: I93e07956b8e29837219d328dacfbd5c6067c1a62

2023-12-23 19:27 UTC, mattsinc requested changes
Beyond the one minor change, I agree with the spirit of this change.  @powerjg should view too though -- I think it's fine to allow int and Addr in SLICC, but I guess it's worth us discussing what the purpose of allow these return types is from SLICC?

2023-12-23 19:27 UTC, mattsinc commented on src/mem/slicc/ast/OperatorExprAST.py
> +            if (
I don't think the formatting of this if matches the formatting elsewhere in the file

2024-01-11 00:57 UTC, powerjg approved these changes
Fine with me :)

2024-01-11 00:57 UTC, powerjg commented
@mattsinc can you re-review since you "requested changes" to allow this to merge?

2024-01-11 07:17 UTC, mattsinc approved these changes

2024-01-12 18:02 UTC, merged