Ostream helpers
gem5/gem5 pull request #77
Opened 2023-07-13 14:39 UTC by MeatBoy106

Refinements, tests and extra features for ostream helpers. Most of these imported and updated from Gerrit submission.

2023-07-13 17:20 UTC, powerjg approved these changes, later dismissed

2023-07-13 18:38 UTC, giactra requested changes
Sorry to stop the merging process. Overall LGTM but I have a minor request

2023-07-13 18:38 UTC, giactra commented on src/base/stl_helpers/ostream_helpers.test.cc
> +    auto helpedRepresentation = [](const auto& val) {
Nit: this should be lower case instead of lower camel case being a local variable

2023-07-13 18:38 UTC, giactra commented on src/base/stl_helpers/ostream_helpers.test.cc
> +    auto expectedRepresentation = [&](const auto& ptr) {
Ditto

2023-07-13 18:38 UTC, giactra commented on src/base/stl_helpers/ostream_helpers.test.cc
> +        auto* rawPtr = &*ptr;
Ditto

2023-07-19 19:29 UTC, BobbyRBruce commented
Hey @MeatBoy106 : This isn't a harder requirement but it would help us a little bit if you could add tags to the PR title as well. We're still, for now, enforcing the use of tags and github, by default, uses the PR title as the merge commit header, so it's nice to have that setup for us (when a Maintainer squashes and merges the commit they can choose to edit the header, but that means they choose what the tags are. It's nice if the contributor can do that).

2023-07-20 06:35 UTC, MeatBoy106 commented
@BobbyRBruce Sure! Is it better that way?

2023-07-20 17:40 UTC, BobbyRBruce commented
> @BobbyRBruce Sure! Is it better that way?

Yes. Thank you!

2023-07-20 17:40 UTC, BobbyRBruce approved these changes

2023-07-20 17:41 UTC, BobbyRBruce commented
I'll merge this when @giactra has approved.

2023-07-21 15:35 UTC, giactra approved these changes
Thanks for the change

2023-07-21 18:11 UTC, merged