base: Fix Integer overflow in AddrRange
gem5/gem5 pull request #786
Opened 2024-01-18 22:24 UTC by Harshil2107

This PR fixes the bug mentioned in #240.

Change-Id: I32139fa37b741185ba766d49dfa8cdab34f19010

2024-01-21 16:49 UTC, pranith requested changes

2024-01-21 16:49 UTC, pranith commented on src/base/addr_range.test.cc
> +    /* An issue raised in https://github.com/gem5/gem5/issues/240 where if an
This comment can be copied into the commit message to make the motivation clearer.

2024-01-23 06:37 UTC, pranith approved these changes

2024-01-23 19:38 UTC, powerjg approved these changes

2024-01-25 18:18 UTC, merged