configs: fix GPU's default number of HW barrier/CU
gem5/gem5 pull request #82
Opened 2023-07-14 04:19 UTC by KaiBatley

AMD GCN3 and Vega GPUs assume a max of 16 WG/CU.  Any GPU WG with more than 1 WF requires a hardware barrier to allow WFs in the WG to synchronize locally.  However, currently the default gem5 GPU configuration assumes only 4 barriers per CU, which artificially prevents applications with > 4 WG/CU that could run simultaneously from running simultaneously.

This fix resolves this by updating the default number of hardware barriers per CU to 16, which mimics the support described in slide 39 here: https://www.olcf.ornl.gov/wp-content/uploads/2019/10/ORNL_Application_Readiness_Workshop-AMD_GPU_Basics.pdf

2023-07-14 06:00 UTC, mattsinc approved these changes

2023-07-14 06:06 UTC, mattsinc commented
@KaiBatley : it looks like you forgot to add a change ID, as the second check fails with this:

None of the commits in this pull request contains a Change-ID, which we require for any changes made to gem5.  To automatically insert one, run the following:\n f=.git/hooks/commit-msg ; mkdir -p  ;  curl -Lo  https://gerrit-review.googlesource.com/tools/hooks/commit-msg ; chmod +x \n Then amend the commit with git commit --amend --no-edit, and update your pull request.

You'll have to update this before anything further can happen.

2023-07-14 06:08 UTC, mattsinc requested changes
You'll also need to update the commit message to be 80 characters per line

2023-07-14 13:41 UTC, BobbyRBruce commented
The current test failing in our CI is due to the pull-request not containing a change ID. The easiest way to solve this is with the following:

```sh
n f=.git/hooks/commit-msg ; mkdir -p  ;  curl -Lo  https://gerrit-review.googlesource.com/tools/hooks/commit-msg ; chmod +x \n
git commit --amend --no-edit
```

This will add a change ID to the commit at the HEAD of the pull request. 

To avoid this going forward we strongly recommend using our pre-commit git hooks. To install execute `util/pre-commit-install.sh` in the gem5 repo. These git hooks  automatically add Change-IDs to a commit and run our style checks on code you have added or altered.

2023-07-15 05:46 UTC, closed without merging

2023-07-15 06:08 UTC, KaiBatley commented
#92 Replaces this pull request to fix the issues.