tests: Add compiler test for gcc 13
gem5/gem5 pull request #858
Opened 2024-02-06 23:49 UTC by Harshil2107

Change-Id: I41bdf3ab7ffff21c4148ef17fc5229b5597ec953

2024-02-08 19:16 UTC, BobbyRBruce requested changes
In addition to my comments here: You need to replace the latest clang version in the `latest-compilers-all-gem5-builds` job with `clang-version-13` (in the compiler-tests.yaml).

I'll upload the docker image ASAP. My requested changes shouldn't really impact the behavior of the image.

2024-02-08 19:16 UTC, BobbyRBruce commented on util/dockerfiles/ubuntu-22.04_gcc_13-version/Dockerfile
> +ARG version
Let's keep this simple. Just remove the ARG version here and hard-code the versions in this file.

2024-02-08 19:16 UTC, BobbyRBruce commented on util/dockerfiles/ubuntu-22.04_gcc_13-version/Dockerfile
> +    add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
I'd add a comment here explaining this is necessary to get gcc Version 13

2024-02-08 19:16 UTC, BobbyRBruce commented on util/dockerfiles/docker-compose.yaml
> +                - version=13
Remove this, i think it's superfluous.

2024-02-08 19:20 UTC, BobbyRBruce commented on util/dockerfiles/ubuntu-22.04_gcc_13-version/Dockerfile
> +    apt -y install software-properties-common && \
Why is this done separately?

2024-02-08 19:20 UTC, BobbyRBruce commented on util/dockerfiles/ubuntu-22.04_gcc_13-version/Dockerfile
> +    apt -y upgrade && \
Is this upgrade necessary? Isn't update sufficient?

2024-02-14 20:11 UTC, BobbyRBruce commented on util/dockerfiles/ubuntu-22.04_gcc_13-version/Dockerfile
> +    apt -y install software-properties-common && \
@Harshil2107  Can you please answer this question.

2024-02-26 18:40 UTC, Harshil2107 commented on util/dockerfiles/ubuntu-22.04_gcc_13-version/Dockerfile
> +    apt -y install software-properties-common && \
I did this because we need software-prperties-common to get the ppa. I will add a comment.

2024-02-26 19:04 UTC, ivanaamit approved these changes
lgtm

2024-02-26 23:03 UTC, BobbyRBruce approved these changes

2024-02-26 23:03 UTC, merged