scons: Disable Address and Undefined Behavior Sanitizers for GCC
gem5/gem5 pull request #951
Opened 2024-03-21 08:22 UTC by BobbyRBruce

This removes the '--with-asan' and '--with-ubsan' are not compatible with GCC. This PR therefore removes them to avoid these issues.

* The `--with-asan` incompatibility with GCC is discussed in Issue #916.

* `scons build/ALL/gem5.opt -j`nproc` --with-ubsan` returns the following error:

```sh
 [     CXX] src/base/loader/image_file_data.cc -> ALL/base/loader/image_file_data.o
In file included from /usr/include/string.h:535,
                 from /usr/include/c++/11/cstring:42,
                 from src/base/cprintf_formats.hh:33,
                 from src/base/cprintf.hh:38,
                 from src/base/logging.hh:49,
                 from src/base/loader/image_file_data.cc:40:
In function ‘char* strcpy(char*, const char*)’,
    inlined from ‘int gem5::loader::doGzipLoad(int)’ at src/base/loader/image_file_data.cc:70:11,
    inlined from ‘gem5::loader::ImageFileData::ImageFileData(const string&)’ atsrc/base/loader/image_file_data.cc:116:24:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:79:33: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ offset [0, 19] is out of the bounds [0, 0] [-Werror=array-bounds]
   79 |   return __builtin___strcpy_chk (__dest, __src, __glibc_objsize (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
scons: *** [build/ALL/base/loader/image_file_data.o] Error 1
scons: building terminated because of errors.
*** Summary of Warnings ***
Warning: Header file <capstone/capstone.h> not found.
         This host has no capstone library installed.
Warning: Couldn't find HDF5 C++ libraries. Disabling HDF5 support.
```

2024-03-21 20:24 UTC, powerjg commented
Isn't that "error" a bug in gem5?

`offset [0, 19] is out of the bounds [0, 0] [-Werror=array-bounds]`

It seems to be unhappy about lines 69 or 70.  I think it's line 70. 

[size_t tmp_len = strlen(P_tmpdir);](https://github.com/gem5/gem5/blob/2b67d0eba6a9dfa12817776fb681b293ee293b4c/src/base/loader/image_file_data.cc#L67-L70)

Upon closer inspection, I think the bounds check is OK, but it's not very good code. We should probably replace the `char *` with a string.

2024-03-21 20:25 UTC, powerjg requested changes
I don't think this is a problem with gcc, I think gcc is telling us something is wrong.

2024-03-22 04:13 UTC, abmerop commented
There is a problem with that file for sure. I was able to make some modifications to remove the warning, but please don't remove ubsan/asan as they have proved to be useful (at least to me) lately

2024-03-22 15:59 UTC, powerjg commented
I think that we *need* to remove the asan for gcc. See https://github.com/gem5/gem5/issues/916 @abmerop do you have a suggestions to fix #916?

Note this patch is not removing it for clang

2024-03-23 18:59 UTC, BobbyRBruce commented
Ok, updated this PR to just removing the Address Sanitizer.

I got a bit ahead of myself also removing the Undefined Behavior Sanitizer too. I'll try to fix it or at least open an issue.

2024-03-23 22:11 UTC, BobbyRBruce commented
The undefined behavior bug is fixed by #959

2024-04-02 21:37 UTC, powerjg approved these changes
I'll go ahead and approve, but before you merge: Does this affect *all* GCC versions or just specific GCC versions?

2024-04-04 18:48 UTC, BobbyRBruce commented
> I'll go ahead and approve, but before you merge: Does this affect _all_ GCC versions or just specific GCC versions?

Yes, I've confirmed this in all gem5 supported versions.

2024-04-04 18:48 UTC, merged

2024-04-08 16:29 UTC, abmerop commented
Out of curiosity, does address sanitizer just not work?  Or is it another code problem with the "new" string check warnings?

2024-04-08 16:53 UTC, BobbyRBruce commented
> Out of curiosity, does address sanitizer just not work? Or is it another code problem with the "new" string check warnings?

The issue related to this is in #916. You can't compiled gem5 with GCC with the address sanitizer. In the issue I highlight some code the Address Sanitizer can't handle.

I don't know what you mean by string check warnings though, i don't think this has anything to do with string checks.

2024-04-08 16:55 UTC, abmerop commented
> I don't know what you mean by string check warnings though, i don't think this has anything to do with string checks.

Hmm.

Ok I will just use clang for it then.